import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { ProductCard } from '@/components/ProductCard';
import { ContentSections } from '@/components/HomeContent';
import { Screen } from '@/components/Screen';
import { Button, Chip, EmptyState, Field } from '@/components/Ui';
import { useShop } from '@/context/ShopContext';
import { availableStock, matchesCategory, productPrice } from '@/lib/commerce';
import { colors } from '@/theme';
export default function Shop(){
 const params=useLocalSearchParams<{category?:string;featured?:string;q?:string}>();const {store,loading,error,reload}=useShop();const {width}=useWindowDimensions();const columns=width>=1000?4:width>=768?3:2;const cardWidth=(Math.min(width,1200)-28-12*(columns-1))/columns;
 const [q,setQ]=useState(params.q||'');const [category,setCategory]=useState(params.category||'all');const [sort,setSort]=useState('featured');const [inStock,setInStock]=useState(false);const [filterOpen,setFilterOpen]=useState(false);const [brand,setBrand]=useState('all');const [min,setMin]=useState('');const [max,setMax]=useState('');
 useEffect(()=>{setCategory(params.category||'all');setQ(params.q||'')},[params.category,params.q]);
 const brands=[...new Set(store.products.map(p=>p.manufacturerBrand).filter(Boolean))];
 const products=useMemo(()=>store.products.filter(p=>p.displayType!=='Reel'&&matchesCategory(p,category)&&(params.featured!=='true'||store.featuredProductIds?.includes(p._id))&&(!q||`${p.name} ${p.sku||''} ${p.manufacturerBrand||''}`.toLowerCase().includes(q.toLowerCase()))&&(!inStock||availableStock(p)>0)&&(brand==='all'||p.manufacturerBrand===brand)&&(!min||productPrice(p)>=Number(min))&&(!max||productPrice(p)<=Number(max))).sort((a,b)=>sort==='low'?productPrice(a)-productPrice(b):sort==='high'?productPrice(b)-productPrice(a):sort==='rating'?Number(b.averageRating||0)-Number(a.averageRating||0):sort==='newest'?String(b.createdAt||b._id).localeCompare(String(a.createdAt||a._id)):0),[store,category,q,sort,inStock,brand,min,max,params.featured]);
 return <Screen><View style={s.top}><View><Text style={s.title}>{params.featured==='true'?'Featured':'Shop all'}</Text><Text style={s.count}>{products.length} products</Text></View><Pressable onPress={()=>setFilterOpen(true)} style={s.filter}><Ionicons name="options-outline" size={20} color={colors.primary}/><Text>Filter</Text></Pressable></View><View style={s.search}><Ionicons name="search" size={20}/><TextInput value={q} onChangeText={setQ} placeholder="Search the catalog" style={{flex:1}}/></View><View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}><Chip label="All" selected={category==='all'} onPress={()=>setCategory('all')}/>{store.categories.map(c=><Chip key={c._id} label={c.name} selected={category===c._id} onPress={()=>setCategory(c._id)}/>)}</ScrollView></View>{error&&<Pressable onPress={reload}><Text style={{padding:14,color:colors.danger}}>{error} · Retry</Text></Pressable>}
 <FlatList key={columns} data={products} keyExtractor={p=>p._id} numColumns={columns} columnWrapperStyle={{gap:12}} contentContainerStyle={s.list} onRefresh={reload} refreshing={loading} renderItem={({item})=><ProductCard product={item} width={cardWidth}/>} ListHeaderComponent={<ContentSections sections={(store.contentSections||[]).filter(s=>s.locations?.includes('products_top_right'))}/>} ListEmptyComponent={loading?<ActivityIndicator color={colors.primary}/>:<EmptyState icon="search-outline" title="No products found" message="Try a different search or clear your filters."/>}/>
 <Modal visible={filterOpen} transparent animationType="slide" onRequestClose={()=>setFilterOpen(false)}><Pressable style={s.scrim} onPress={()=>setFilterOpen(false)}/><View style={s.sheet}><ScrollView contentContainerStyle={{gap:10}}><Text style={s.title}>Filter & sort</Text>{[['featured','Featured'],['newest','Newest'],['low','Price: low to high'],['high','Price: high to low'],['rating','Highest rated']].map(([v,l])=><Pressable key={v} onPress={()=>setSort(v)} style={s.option}><Ionicons name={sort===v?'radio-button-on':'radio-button-off'} size={21} color={colors.primary}/><Text>{l}</Text></Pressable>)}<Pressable onPress={()=>setInStock(x=>!x)} style={s.option}><Ionicons name={inStock?'checkbox':'square-outline'} size={22} color={colors.primary}/><Text>In stock only</Text></Pressable><Field label="Minimum price" value={min} onChangeText={setMin} keyboardType="decimal-pad"/><Field label="Maximum price" value={max} onChangeText={setMax} keyboardType="decimal-pad"/><Text style={{fontWeight:'800'}}>Brand</Text><ScrollView horizontal contentContainerStyle={{gap:8}}><Chip label="All brands" selected={brand==='all'} onPress={()=>setBrand('all')}/>{brands.map(b=><Chip key={b} label={b!} selected={brand===b} onPress={()=>setBrand(b!)}/>)}</ScrollView><Button title="Clear filters" variant="outline" onPress={()=>{setQ('');setCategory('all');setBrand('all');setMin('');setMax('');setInStock(false);setSort('featured')}}/><Button title={`Show ${products.length} products`} onPress={()=>setFilterOpen(false)}/></ScrollView></View></Modal></Screen>;
}
const s=StyleSheet.create({top:{padding:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:27,fontWeight:'900',color:colors.ink},count:{color:colors.muted,marginTop:2},filter:{padding:12,borderRadius:12,backgroundColor:'white',flexDirection:'row',gap:7,alignItems:'center'},search:{marginHorizontal:14,marginBottom:14,height:48,borderRadius:14,backgroundColor:'white',paddingHorizontal:13,flexDirection:'row',alignItems:'center',gap:9},chips:{gap:9,paddingHorizontal:14,paddingBottom:13},list:{padding:14,gap:12,paddingBottom:35},scrim:{...StyleSheet.absoluteFill,backgroundColor:'rgba(0,0,0,.35)'},sheet:{position:'absolute',bottom:0,left:0,right:0,maxHeight:'85%',maxWidth:640,alignSelf:'center',backgroundColor:'white',borderTopLeftRadius:25,borderTopRightRadius:25,padding:22,paddingBottom:35},option:{height:43,flexDirection:'row',alignItems:'center',gap:12}});
