import { Image, ImageBackground, Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { router } from 'expo-router';
import { useShop } from '@/context/ShopContext';
import { mediaUrl } from '@/lib/api';
import { openStoreLink } from '@/lib/navigation';
import { matchesCategory } from '@/lib/commerce';
import { ProductCard } from './ProductCard';
import { SectionTitle } from './Ui';
import { Video } from './Video';
import { colors } from '@/theme';
import type { Product } from '@/types';
export function Banner({item,active=false}:{item:any;active?:boolean}) {
 return <View style={s.banner}>{item.imageUrl?<ImageBackground source={{uri:mediaUrl(item.imageUrl)}} style={s.bannerImage} resizeMode="cover"/>:item.videoUrl?<View style={StyleSheet.absoluteFill}><Video url={item.videoUrl} active={active} height={260}/></View>:null}
 {!item.hideText&&<View style={s.bannerText}><Text style={s.bannerTitle}>{item.title}</Text><Text style={s.bannerSubtitle}>{item.subtitle||item.line1}</Text>{item.line2?<Text style={s.bannerSubtitle}>{item.line2}</Text>:null}<Pressable accessibilityRole="button" onPress={()=>openStoreLink(item.linkUrl||'#/products')} style={s.bannerButton}><Text style={s.buttonText}>{item.buttonText||'Shop now'} →</Text></Pressable></View>}
 {item.hideText&&item.linkUrl&&<Pressable accessibilityLabel={item.title||'Shop this collection'} onPress={()=>openStoreLink(item.linkUrl)} style={StyleSheet.absoluteFill}/>}
 </View>;
}
export function ContentSections({sections}:{sections:any[]}) {
 const {width}=useWindowDimensions();const tablet=width>=768;
 return <View style={{gap:24}}>{sections.map((section,index)=><View key={section._id||index} style={{gap:12}}>{section.title&&<Text style={s.title}>{section.title}</Text>}{section.subtitle&&<Text style={s.muted}>{section.subtitle}</Text>}<View style={s.grid}>{(section.items||[]).map((item:any,i:number)=><View key={item._id||i} style={[s.contentCard,{width:tablet?`${100/Math.min(4,section.columns||2)-2}%`:'100%'}]}>{item.imageUrl&&item.type!=='text'&&<Image source={{uri:mediaUrl(item.imageUrl)}} style={{width:'100%',aspectRatio:item.imageWidth&&item.imageHeight?item.imageWidth/item.imageHeight:1.8}} resizeMode="cover"/>}{item.type!=='image'&&<View style={{padding:16,gap:8}}>{item.title&&<Text style={s.title}>{item.title}</Text>}{item.text&&<Text style={s.muted}>{plainText(item.text)}</Text>}</View>}{item.linkUrl&&<Pressable onPress={()=>openStoreLink(item.linkUrl)} style={{padding:16}}><Text style={s.link}>{item.linkLabel||'Explore'} →</Text></Pressable>}</View>)}</View></View>)}</View>;
}
export const plainText=(html='')=>html.replace(/<\/(p|div|h[1-6]|li)>|<br\s*\/?\s*>/gi,'\n').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").trim();
export function ProductGrid({products,columns=2}:{products:Product[];columns?:number}) {
 const {width}=useWindowDimensions();const container=Math.min(width,1200)-32;const count=width>=768?Math.min(5,Math.max(3,columns)):Math.min(3,Math.max(1,columns));const cardWidth=(container-(count-1)*12)/count;
 return <View style={s.grid}>{products.map(p=><ProductCard key={p._id} product={p} width={cardWidth}/>)}</View>;
}
export function HomeSection({section}:{section:any}) {
 const {store}=useShop();const {width}=useWindowDimensions();const products=store.products.filter(p=>p.displayType!=='Reel');const settings=store.settings;
 if(section.type==='shipping_info')return settings.showBenefitItems===false?null:<View style={s.grid}>{(settings.benefitItems?.length?settings.benefitItems:[{title:'Free Shipping',text:'Free delivery for orders above your store threshold.'},{title:'24/7 Support',text:'Fast help for product, delivery, and return questions.'},{title:'Easy Returns',text:'Simple exchanges and refunds with clear tracking.'}]).map((item:any,i:number)=><View key={i} style={[s.benefit,{flexBasis:width>=768?'23%':'46%'}]}><Text style={s.link}>✓</Text><Text style={s.benefitTitle}>{item.title}</Text><Text style={s.muted}>{item.text}</Text></View>)}</View>;
 if(section.type==='browse_collections'){
  const ids=section.categories?.length?section.categories.map((c:any)=>String(c._id||c)):[];
  const categories=store.categories.filter(c=>(!ids.length||ids.includes(c._id))&&products.some(p=>matchesCategory(p,c._id)));
  return <View><SectionTitle title={section.title||'Browse collections'} action="See all" onAction={()=>router.push('/categories')}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:12}}>{categories.map(c=><Pressable key={c._id} onPress={()=>router.push({pathname:'/(tabs)/shop',params:{category:c._id}})} style={s.category}><Image source={{uri:mediaUrl(c.imageUrl||products.find(p=>matchesCategory(p,c._id))?.mainImage)}} style={s.categoryImage}/><Text style={s.benefitTitle}>{c.name}</Text></Pressable>)}</ScrollView></View>;
 }
 if(section.type==='seasonal_banner')return <ContentSections sections={(store.contentSections||[]).filter(s=>s.locations?.includes('home_before_new_arrivals')&&s.items?.some((i:any)=>i.imageUrl))}/>;
 if(section.type==='new_arrivals')return <View style={{gap:24}}><View><SectionTitle title={section.title||'New arrivals'} action="View all" onAction={()=>router.push('/(tabs)/shop')}/>{section.subtitle&&<Text style={s.muted}>{section.subtitle}</Text>}<ProductGrid products={products.slice(0,Math.max(6,(section.columns||3)*2))} columns={width>=768?(section.columns||3):(settings.mobileProductGridSize||2)}/></View>{!!store.featuredProducts.length&&<View><SectionTitle title="Featured products" action="View all" onAction={()=>router.push({pathname:'/(tabs)/shop',params:{featured:'true'}})}/><ScrollView horizontal contentContainerStyle={{gap:12}} showsHorizontalScrollIndicator={false}>{store.featuredProducts.map(p=><ProductCard key={p._id} product={p}/>)}</ScrollView></View>}</View>;
 if(section.type==='category_products')return <View style={{gap:24}}>{(section.categories?.length?section.categories:[section.category]).filter(Boolean).map((c:any)=>{const id=String(c._id||c);const list=products.filter(p=>matchesCategory(p,id)).slice(0,section.productLimit||6);return list.length?<View key={id}><SectionTitle title={store.categories.find(c=>c._id===id)?.name||section.title||'Category picks'} action="View all" onAction={()=>router.push({pathname:'/(tabs)/shop',params:{category:id}})}/>{section.subtitle&&<Text style={s.muted}>{section.subtitle}</Text>}<ProductGrid products={list} columns={width>=768?(section.columns||3):(section.mobileColumns||2)}/></View>:null})}</View>;
 if(section.type==='promo_banner')return settings.promoBanner?.isActive===false?null:<Banner item={settings.promoBanner||{}}/>;
 if(section.type==='custom_content')return <ContentSections sections={[section]}/>;
 if(section.type==='custom_banner')return <View style={{gap:12}}>{(section.items?.some((i:any)=>i.imageUrl)?section.items:[section.banner]).filter((i:any)=>i?.imageUrl).map((i:any,index:number)=><Pressable key={index} onPress={()=>i.linkUrl&&openStoreLink(i.linkUrl)}><Image source={{uri:mediaUrl(i.imageUrl)}} style={{width:'100%',aspectRatio:i.imageWidth&&i.imageHeight?i.imageWidth/i.imageHeight:2.3,borderRadius:18}} resizeMode="contain"/></Pressable>)}</View>;
 if(section.type==='blog')return <View><SectionTitle title={section.title||'From the journal'}/>{section.subtitle&&<Text style={s.muted}>{section.subtitle}</Text>}<ScrollView horizontal contentContainerStyle={{gap:14}} showsHorizontalScrollIndicator={false}>{(store.blogPosts||[]).map(post=><Pressable key={post._id||post.slug} style={s.blog} onPress={()=>router.push({pathname:'/blog/[slug]',params:{slug:post.slug}})}><Image source={{uri:mediaUrl(post.coverImage||post.imageUrl||post.featuredImage)}} style={{height:150,width:'100%'}}/><View style={{padding:14,gap:8}}><Text style={s.benefitTitle}>{post.title}</Text><Text numberOfLines={3} style={s.muted}>{plainText(post.excerpt||post.summary)}</Text></View></Pressable>)}</ScrollView><ContentSections sections={(store.contentSections||[]).filter(s=>s.locations?.includes('home_after_blog'))}/></View>;
 if(section.type==='instagram')return <View style={{gap:14}}><Text style={s.title}>Follow on Instagram</Text><Text style={s.link}>@commerceops.store</Text><ScrollView horizontal contentContainerStyle={{gap:12}}>{[1,2,3,4,5,6].map(i=><Pressable key={i} onPress={()=>router.push('/contact')}><Image source={{uri:mediaUrl(`/images/e-commerce/home/insta${i}.jpg`)}} style={{width:150,height:150,borderRadius:14}}/></Pressable>)}</ScrollView></View>;
 return null;
}
const s=StyleSheet.create({grid:{flexDirection:'row',flexWrap:'wrap',gap:12},title:{fontSize:21,fontWeight:'800',color:colors.ink},muted:{color:colors.muted,lineHeight:22,marginBottom:8},link:{color:colors.primary,fontWeight:'800'},contentCard:{backgroundColor:'white',borderRadius:16,overflow:'hidden'},banner:{minHeight:260,borderRadius:22,overflow:'hidden',backgroundColor:colors.primaryDark},bannerImage:{...StyleSheet.absoluteFill},bannerText:{padding:24,backgroundColor:'rgba(0,35,15,.5)',gap:8,minHeight:260,justifyContent:'center'},bannerTitle:{color:'white',fontSize:30,fontWeight:'900',maxWidth:520},bannerSubtitle:{color:'white',fontSize:15,lineHeight:22,maxWidth:520},bannerButton:{backgroundColor:'white',borderRadius:12,padding:13,alignSelf:'flex-start',marginTop:8},buttonText:{color:colors.primary,fontWeight:'800'},benefit:{backgroundColor:'white',padding:16,borderRadius:14,gap:6,flexGrow:1},benefitTitle:{fontWeight:'800',color:colors.ink,fontSize:15},category:{width:130,gap:8},categoryImage:{width:130,height:120,borderRadius:16,backgroundColor:colors.primarySoft},blog:{width:260,borderRadius:16,backgroundColor:'white',overflow:'hidden'}});
