import { useState } from "react";

export default function ForgotPasswordForm({ identifierLabel = "Email address", identifierType = "text", initialIdentifier = "", passwordDigits = false, onRequest, onReset, onBack }) {
  const [form, setForm] = useState({ identifier: initialIdentifier, code: "", password: "", confirmPassword: "" });
  const [step, setStep] = useState("request");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const run = async (action) => { setBusy(true); setMessage(""); try { await action(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const requestCode = (event) => { event.preventDefault(); run(async () => { const result = await onRequest(form.identifier); setMessage(`${result.message}${result.resetCode ? ` Reset code: ${result.resetCode}` : ""}`); if (result.resetCode) setForm((current) => ({ ...current, code: result.resetCode })); setStep("reset"); }); };
  const reset = (event) => { event.preventDefault(); if (form.password !== form.confirmPassword) return setMessage("Passwords do not match."); run(async () => { const result = await onReset({ identifier: form.identifier, code: form.code, password: form.password }); setMessage(result.message); setStep("done"); }); };

  if (step === "done") return <div className="formGrid"><div className="notice">{message}</div><button className="primaryButton" type="button" onClick={onBack}>Return to sign in</button></div>;
  if (step === "request") return <form className="formGrid" onSubmit={requestCode}><p>Enter your account identifier. We’ll send a 6-digit reset code to the registered email address.</p><label>{identifierLabel}<input type={identifierType} autoComplete="username" required value={form.identifier} onChange={(event) => setForm({ ...form, identifier: event.target.value })} /></label>{message && <div className="notice">{message}</div>}<button className="primaryButton" disabled={busy}>{busy ? "Sending…" : "Send reset code"}</button><button className="linkButton" type="button" onClick={onBack}>Back to sign in</button></form>;
  return <form className="formGrid" onSubmit={reset}>{message && <div className="notice">{message}</div>}<label>6-digit reset code<input inputMode="numeric" pattern="\d{6}" maxLength="6" required value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.replace(/\D/g, "").slice(0, 6) })} /></label><label>New password<input type="password" minLength={passwordDigits ? 4 : 8} inputMode={passwordDigits ? "numeric" : undefined} pattern={passwordDigits ? "\d{4}" : undefined} required value={form.password} onChange={(event) => setForm({ ...form, password: passwordDigits ? event.target.value.replace(/\D/g, "").slice(0, 4) : event.target.value })} /></label><label>Confirm password<input type="password" required value={form.confirmPassword} onChange={(event) => setForm({ ...form, confirmPassword: passwordDigits ? event.target.value.replace(/\D/g, "").slice(0, 4) : event.target.value })} /></label>{form.confirmPassword && form.password !== form.confirmPassword && <span className="errorText">Passwords do not match.</span>}<button className="primaryButton" disabled={busy || form.password !== form.confirmPassword}>{busy ? "Resetting…" : "Reset password"}</button><button className="linkButton" type="button" onClick={() => setStep("request")}>Request another code</button></form>;
}
