import { useState } from "react";
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from "recharts";
import { ShoppingCart, IndianRupee, PackageCheck, WalletCards, Check, X, RotateCcw, Share2, Heart, FileText, Gift, Bell, ChevronRight, Download, Tag } from "lucide-react";
import { showToast } from "../utils/toast.js";
import SupportTickets from "./SupportTickets.jsx";

const money = value => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(Number(value) || 0);
const sum = (rows, get) => rows.reduce((total, row) => total + (Number(get(row)) || 0), 0);
const isReturn = order => /return|rto/i.test(order.status);
const date = value => value && !Number.isNaN(new Date(value).getTime()) ? new Date(value).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }) : "—";
const earning = order => order.resellerAttribution?.finalEarning ?? order.resellerAttribution?.earning ?? 0;
function Empty({ children }) { return <p className="rsEmpty">{children}</p>; }
function Lead({ title, children }) { return <div className="resellerPageLead"><div><h2>{title}</h2><p>{children}</p></div></div>; }
function salesData(orders, days) {
  const today = new Date(); today.setHours(0, 0, 0, 0);
  return Array.from({ length: days }, (_, index) => {
    const start = new Date(today); start.setDate(today.getDate() - days + index + 1);
    const end = new Date(start); end.setDate(end.getDate() + 1);
    return { date: start.toLocaleDateString("en-IN", { day: "numeric", month: "short" }), sales: sum(orders.filter(order => new Date(order.createdAt) >= start && new Date(order.createdAt) < end && !/cancel|return|rto/i.test(order.status)), order => order.grandTotal) };
  });
}
function SalesChart({ orders }) {
  const [days, setDays] = useState(30);
  return <article className="resellerPanel rsChart"><header><h3>Sales Overview</h3></header><div className="rsTabs" aria-label="Sales period">{[7, 30, 90].map(value => <button key={value} aria-pressed={days === value} className={days === value ? "active" : ""} onClick={()=>setDays(value)}>{value} Days</button>)}</div><div className="rsChartCanvas"><ResponsiveContainer width="100%" height="100%"><AreaChart data={salesData(orders, days)} margin={{ top: 12, right: 16, bottom: 8, left: 0 }}><defs><linearGradient id="rsSalesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4261de" stopOpacity={0.24}/><stop offset="100%" stopColor="#4261de" stopOpacity={0.02}/></linearGradient></defs><CartesianGrid stroke="#edf0f7" vertical={false}/><XAxis dataKey="date" minTickGap={40} tick={{ fontSize: 10 }} axisLine={false} tickLine={false}/><YAxis width={52} tick={{ fontSize: 10 }} tickFormatter={v=>`₹${v >= 1000 ? `${v/1000}k` : v}`} axisLine={false} tickLine={false}/><Tooltip formatter={value=>[money(value), "Sales"]}/><Area type="monotone" dataKey="sales" stroke="#3656d4" strokeWidth={2.5} fill="url(#rsSalesFill)"/></AreaChart></ResponsiveContainer></div><p className="rsChartNote">Sales exclude cancelled, returned and RTO orders.</p></article>;
}
function EarningsChart({ wallet, dashboard, withdrawals }) {
  const rows = [{ name: "Available", value: Number(wallet.balance)||0, color: "#36b777" }, { name: "Pending earnings", value: Number(dashboard?.pendingEarnings)||0, color: "#ffa21c" }, { name: "Withdrawn", value: sum(withdrawals.filter(row=>row.status === "paid"), row=>row.amount), color: "#4542c7" }];
  const total = sum(rows, row=>row.value);
  return <article className="resellerPanel rsChart"><header><h3>Earnings Summary</h3></header><div className="rsEarningsChart"><div className="rsDonut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={total ? rows : [{value:1,color:"#edf0f7"}]} dataKey="value" innerRadius="70%" outerRadius="94%" startAngle={90} endAngle={-270} strokeWidth={3}>{(total ? rows : [{color:"#edf0f7"}]).map((row,i)=><Cell key={i} fill={row.color}/>)}</Pie>{total > 0 && <Tooltip formatter={money}/>}</PieChart></ResponsiveContainer><div><strong>{money(total)}</strong><small>Balance summary</small></div></div><ul>{rows.map(row=><li key={row.name}><i style={{background:row.color}}/><span>{row.name}<strong>{money(row.value)} <small>({total ? Math.round(row.value/total*100) : 0}%)</small></strong></span></li>)}</ul></div><p className="rsChartNote">Requested withdrawals are shown in Wallet / Withdraw.</p></article>;
}
function topProducts(orders) {
  const result = new Map();
  orders.filter(order=>!/cancel|return|rto/i.test(order.status)).forEach(order=>order.items?.forEach(item=>{ const name=item.name || "Product"; const row=result.get(name)||{name,quantity:0}; row.quantity+=Number(item.quantity)||0; result.set(name,row); }));
  return [...result.values()].sort((a,b)=>b.quantity-a.quantity);
}
export function DashboardOverview({ dashboard, orders, wallet, withdrawals, products, links, navigate }) {
  const cards = [
    ["Total Orders", orders.length, ShoppingCart, "blue", "orders"],
    ["Total Sales", money(sum(orders.filter(row=>!/cancel|return|rto/i.test(row.status)), row=>row.grandTotal)), IndianRupee, "green", "performance"],
    ["My Earnings", money(dashboard?.totalEarnings), PackageCheck, "orange", "earnings"],
    ["Pending Earnings", money(dashboard?.pendingEarnings), FileText, "purple", "earnings"],
    ["Available Balance", money(wallet.balance), WalletCards, "blue", "payouts"],
    ["Delivered Orders", orders.filter(row=>row.status === "Delivered").length, Check, "green", "orders"],
    ["Cancelled Orders", orders.filter(row=>row.status === "Cancelled").length, X, "red", "orders"],
    ["Return / RTO Orders", orders.filter(isReturn).length, RotateCcw, "orange", "returns"]
  ];
  const top=topProducts(orders).slice(0,3);
  return <section className="rsOverview"><Lead title="Dashboard Overview">Your business at a glance</Lead><section className="resellerDashboardStats">{cards.map(([label,value,Icon,color,view],index)=><article className={color} key={label}><i><Icon/></i><span>{label}</span><strong>{value}</strong><button onClick={()=>navigate(view)}>{index < 4 ? "View Details" : "View"}<ChevronRight size={15}/></button></article>)}</section><div className="rsTwoColumns"><SalesChart orders={orders}/><EarningsChart wallet={wallet} dashboard={dashboard} withdrawals={withdrawals}/><article className="resellerPanel resellerRecentOrders"><header><h3>Recent Orders</h3><button onClick={()=>navigate("orders")}>View All</button></header>{orders.slice(0,3).map(order=><div key={order._id}><span className="rsOrderIcon"><ShoppingCart size={20}/></span><span><strong>{order.orderNumber}</strong><small>{date(order.createdAt)}</small></span><b className={`resellerStatus ${String(order.status).toLowerCase()}`}>{order.status}</b><em>{money(order.grandTotal)}</em></div>)}{!orders.length&&<Empty>Orders from your shared links will appear here.</Empty>}</article><article className="resellerPanel resellerTopProducts"><header><h3>Top Selling Products</h3><button onClick={()=>navigate("performance")}>View All</button></header>{top.map((row,index)=>{const product=products.find(p=>p.name===row.name);return <div key={row.name}>{product?.mainImage ? <img src={product.mainImage} alt=""/> : <span className="rsOrderIcon"><PackageCheck/></span>}<span><strong>{index+1}. {row.name}</strong><small>Sold: {row.quantity}</small></span></div>})}{!top.length&&<Empty>Your best selling products will appear after your first sale.</Empty>}</article></div><article className="resellerPanel rsQuickActions"><h3>Quick Actions</h3><div>{[["Share Product",Share2,"links"],["Add to Wishlist",Heart,"wishlist"],["My Orders",FileText,"orders"],["Withdraw Money",WalletCards,"payouts"],["Referral & Rewards",Gift,"referrals"],["Offers",Bell,"offers"]].map(([label,Icon,view])=><button key={view} onClick={()=>navigate(view)}><i><Icon/></i><span>{label}</span></button>)}</div></article><div className="resellerReferralBanner"><Gift/><div><h3>Discover your next bestseller</h3><p>Explore products and available margins to grow your earnings.</p></div><button onClick={()=>navigate("offers")}>View Offers</button></div></section>;
}
export function ResellerOrders({ orders, returnsOnly, onSupport }) {
  const [filter,setFilter]=useState("All"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState(null);
  const statuses=returnsOnly ? ["All","Return Requested","Returned","RTO"] : ["All","New","Processing","Shipped","Out for Delivery","Delivered","Cancelled","RTO","Returned","Return Requested"];
  const source=returnsOnly ? orders.filter(isReturn) : orders;
  const matches=source.filter(row=>(filter === "All" || (filter === "New" ? ["Placed","Pending"].includes(row.status) : filter === "Processing" ? ["Confirmed","Packed","Processing"].includes(row.status) : row.status===filter)) && `${row.orderNumber} ${row.items?.map(i=>i.name).join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  return <><Lead title={returnsOnly ? "Returns / RTO" : "My Orders"}>{returnsOnly ? "Track returns and return-to-origin orders. Contact support for assistance." : "Track every order placed through your selling links."}</Lead><div className="rsTabs">{statuses.map(item=><button key={item} className={filter===item?"active":""} aria-pressed={filter===item} onClick={()=>setFilter(item)}>{item}</button>)}</div><input className="rsSearch" aria-label="Search orders" placeholder="Search order number or product…" value={query} onChange={e=>setQuery(e.target.value)}/><section className="resellerPanel resellerOrderTable"><table><thead><tr><th>Order</th><th>Date</th><th>Status</th><th>Order value</th><th>Earning</th><th>Details</th></tr></thead><tbody>{matches.map(order=><tr key={order._id}><td><strong>{order.orderNumber}</strong></td><td>{date(order.createdAt)}</td><td><span className={`resellerStatus ${String(order.status).toLowerCase()}`}>{order.status}</span></td><td>{money(order.grandTotal)}</td><td>{money(earning(order))}</td><td><button className="rsTextButton" onClick={()=>setSelected(order)}>View details</button></td></tr>)}{!matches.length&&<tr><td colSpan="6"><Empty>No orders match this filter.</Empty></td></tr>}</tbody></table></section>{selected&&<section className="resellerPanel rsSection"><header><h3>{selected.orderNumber}</h3><button onClick={()=>setSelected(null)}>Close</button></header><p>Status: <strong>{selected.status}</strong> · Earnings status: {selected.resellerAttribution?.status?.replaceAll("_"," ") || "Pending"}</p>{selected.items?.map((item,i)=><p key={i}>{item.name} × {item.quantity}</p>)}<button className="resellerPrimary" onClick={onSupport}>Get order / return support</button></section>}</>;
}
function downloadCsv(name, rows) {
  const csv=rows.map(row=>row.map(value=>{let text=String(value??"");if(/^[=+\-@\t\r]/.test(text))text=`'${text}`;return `"${text.replaceAll('"','""')}"`;}).join(",")).join("\r\n");
  const url=URL.createObjectURL(new Blob(["\uFEFF",csv],{type:"text/csv;charset=utf-8;"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function ResellerInsights({ orders, links, reports }) {
  const clicks=sum(links,row=>row.clicks); const top=topProducts(orders);
  return <><Lead title={reports ? "Reports" : "My Performance"}>Sales, earnings and product performance from your reseller activity.</Lead>{reports?<div className="rsReportGrid">{[["Sales report",["Order","Date","Status","Sales"],orders.map(row=>[row.orderNumber,date(row.createdAt),row.status,row.grandTotal])],["Earnings report",["Order","Earning","Status"],orders.map(row=>[row.orderNumber,earning(row),row.resellerAttribution?.status])],["Product report",["Product","Units sold"],top.map(row=>[row.name,row.quantity])]].map(([name,head,rows])=><article className="resellerPanel rsSection" key={name}><FileText/><h3>{name}</h3><p>{rows.length} records · CSV download</p><button className="resellerPrimary" onClick={()=>downloadCsv(`${name.toLowerCase().replaceAll(" ","-")}.csv`,[head,...rows])}><Download size={16}/> Download</button></article>)}</div>:<><div className="rsMetricGrid">{[["Link visits",clicks],["Orders",orders.length],["Conversion rate",clicks?`${(orders.length/clicks*100).toFixed(1)}%`:"—"],["Order earnings",money(sum(orders,earning))]].map(([label,value])=><article className="resellerPanel rsSection" key={label}><small>{label}</small><h2>{value}</h2></article>)}</div><SalesChart orders={orders}/></>}<section className="resellerPanel rsSection"><h3>Best Selling Products</h3>{top.map(row=><p key={row.name}>{row.name}<strong className="rsFloatRight">{row.quantity} sold</strong></p>)}{!top.length&&<Empty>No product sales yet.</Empty>}</section></>;
}
export function ResellerSupport() {
  return <><Lead title="Help & Support">Get help with orders, returns, earnings or your account.</Lead><SupportTickets accountType="Customer" preserveRoute/><article className="resellerPanel rsSection"><h3>Help Center</h3>{[["When are earnings available?","Margins are credited after delivery and the order return window closes."],["How do I withdraw?","Save your bank details in My Profile, then submit a request from Wallet / Withdraw."],["How do I share a product?","Choose Set Margin, select a product, set your margin and create your selling link."],["Need help with a return?","Open Returns / RTO to find the order. Select the return category in your support ticket and include the order number in your message."]].map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</article></>;
}

function readSaved(key, fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
export function ResellerExtras({ view, account, products, orders, withdrawals, links, navigate, onSelect, copy }) {
  const storageKey=`reseller:${account._id}:wishlist`;
  const [saved,setSaved]=useState(()=>{const value=readSaved(storageKey,[]);return Array.isArray(value)?value:[]});
  const [query,setQuery]=useState("");const [savedOnly,setSavedOnly]=useState(true);const [notice,setNotice]=useState("");
  const [read,setRead]=useState(()=>readSaved(`reseller:${account._id}:read`,[]));
  function toggle(id){const next=saved.includes(id)?saved.filter(value=>value!==id):[...saved,id];setSaved(next);try{localStorage.setItem(storageKey,JSON.stringify(next));showToast(saved.includes(id)?"Product removed from wishlist.":"Product added to wishlist.")}catch{setNotice("Browser storage is unavailable. Changes last for this visit only.")}}
  if(view === "wishlist" || view === "offers") {
    const offers=view==="offers";const rows=products.filter(product=>(offers ? Number(product.resellerPricing?.maximumMargin)>0 : !savedOnly || saved.includes(product._id)) && product.name?.toLowerCase().includes(query.toLowerCase()));
    return <><Lead title={offers?"Offers & Promotions":"Wishlist"}>{offers?"Explore available earning margins. Special campaigns will appear when available.":"Save products for later. Your wishlist is stored in this browser."}</Lead>{notice&&<p role="status">{notice}</p>}<div className="rsTabs">{!offers&&<><button className={savedOnly?"active":""} onClick={()=>setSavedOnly(true)}>Saved products ({saved.length})</button><button className={!savedOnly?"active":""} onClick={()=>setSavedOnly(false)}>Browse products</button></>}</div><input className="rsSearch" aria-label="Search products" placeholder="Search products…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="resellerCatalogGrid">{rows.map(product=><article key={product._id}>{product.mainImage&&<img src={product.mainImage} alt={product.name}/>}<div><small>{offers?"AVAILABLE RESELLER MARGIN":"SAVE & SHARE"}</small><h3>{product.name}</h3><p>Base price: {money(product.resellerPricing?.basePrice)}</p><p>Earn up to <strong>{money(product.resellerPricing?.maximumMargin)}</strong> per sale</p><footer><button aria-label={`${saved.includes(product._id)?"Remove":"Save"} ${product.name}`} aria-pressed={saved.includes(product._id)} onClick={()=>toggle(product._id)}><Heart fill={saved.includes(product._id)?"currentColor":"none"}/> {saved.includes(product._id)?"Saved":"Save"}</button><button onClick={()=>onSelect(product)}>Set Margin</button></footer></div></article>)}{!rows.length&&<Empty>{offers?"No products with earning margins are currently available.":"No saved products match. Browse products to add your favorites."}</Empty>}</div></>;
  }
  if(view === "notifications") {
    const rows=[...orders.map(row=>({id:`order-${row._id}-${row.status}`,title:`${row.orderNumber} · ${row.status}`,description:`Order value ${money(row.grandTotal)}`,date:row.updatedAt||row.createdAt,target:"orders"})),...withdrawals.map(row=>({id:`withdrawal-${row._id}-${row.status}`,title:`Withdrawal ${row.status}`,description:money(row.amount),date:row.updatedAt||row.createdAt,target:"payouts"}))].sort((a,b)=>new Date(b.date)-new Date(a.date));
    return <><Lead title="Notifications">Order and payment activity from your account.</Lead><button className="resellerPrimary" onClick={()=>{const ids=rows.map(row=>row.id);setRead(ids);try{localStorage.setItem(`reseller:${account._id}:read`,JSON.stringify(ids));showToast("Notifications marked as read.")}catch{setNotice("Read status could not be saved in this browser.")}}}>Mark all as read</button>{notice&&<p role="status">{notice}</p>}<section className="resellerPanel rsSection">{rows.map(row=><button className={`rsNotification ${Array.isArray(read)&&read.includes(row.id)?"read":""}`} key={row.id} onClick={()=>navigate(row.target)}><Bell/><span><strong>{row.title}</strong><small>{row.description} · {date(row.date)}</small></span><ChevronRight/></button>)}{!rows.length&&<Empty>You’re all caught up. Order and withdrawal updates will appear here.</Empty>}</section></>;
  }
  if(view === "referrals") return <><Lead title="Referral & Rewards">Invite your network to discover reselling.</Lead><section className="resellerPanel rsSection"><Gift size={36}/><h3>Grow together with HRSBasket</h3><p>Reseller referral tracking and reward payouts are not currently enabled. You can share the registration page with friends.</p><label className="rsLinkLabel">Registration link<input readOnly value={`${window.location.origin}/#/reseller/register`}/></label><button className="resellerPrimary" onClick={()=>copy(`${window.location.origin}/#/reseller/register`)}>Copy invitation link</button></section></>;
  if(view === "marketing") return <><Lead title="Marketing Tools">Create a message for your existing product links.</Lead><section className="resellerPanel rsSection">{links.map(link=><div className="rsMarketingRow" key={link._id}><h3>{link.product?.name||"Product"}</h3><p>{link.url||`${window.location.origin}/#/resell/${link.code}`}</p><button className="resellerPrimary" onClick={()=>copy(`${link.product?.name||"Discover this product"} — ${money(link.customerPrice)}\n${link.url||`${window.location.origin}/#/resell/${link.code}`}`)}>Copy sharing message</button></div>)}{!links.length&&<><Empty>Create your first product link to generate a sharing message.</Empty><button className="resellerPrimary" onClick={()=>navigate("add")}>Create product link</button></>}</section></>;
  return <><Lead title="Settings">Manage your reseller account and preferences.</Lead><section className="resellerPanel rsSection"><h3>Account</h3><p>{account.fullName} · {account.resellerId}</p><p>{account.email}</p><button className="resellerPrimary" onClick={()=>navigate("profile")}>Manage bank details</button><h3>Local preferences</h3><p>Wishlist and read notifications are saved in this browser.</p><button className="rsTextButton" onClick={()=>{try{localStorage.removeItem(storageKey);localStorage.removeItem(`reseller:${account._id}:read`);setNotice("Wishlist and notification preferences cleared.");showToast("Wishlist and notification preferences cleared.")}catch{setNotice("Could not clear browser preferences.")}}}>Clear local wishlist and read status</button>{notice&&<p role="status">{notice}</p>}</section></>;
}
