import { useEffect, useState } from "react";
import { MessageSquareText, Plus, X } from "lucide-react";
import { api } from "../services/api.js";

const adapters = {
  Customer: [api.customerTickets, api.createCustomerTicket, api.replyCustomerTicket],
  Seller: [api.sellerTickets, api.createSellerTicket, api.replySellerTicket],
  Partner: [api.partnerTickets, api.createPartnerTicket, api.replyPartnerTicket]
};

export default function SupportTickets({ accountType, orders = [], preserveRoute = false }) {
  const [listTickets, createTicket, replyTicket] = adapters[accountType];
  const [tickets, setTickets] = useState([]); const [selected, setSelected] = useState(null); const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [reply, setReply] = useState("");
  const [form, setForm] = useState({ subject: "", category: "general", orderId: "", priority: "normal", message: "" });
  const load = async () => { const rows = await listTickets(); setTickets(rows); setSelected((current) => current ? rows.find((row) => row._id === current._id) || null : null); };
  useEffect(() => { load().catch((error) => setMessage(error.message)); }, [accountType]);
  useEffect(() => { const onBack = () => { if (!window.location.hash.includes("/tickets/")) setSelected(null); }; window.addEventListener("popstate", onBack); return () => window.removeEventListener("popstate", onBack); }, []);
  const openTicket = (ticket) => { setSelected(ticket); if (!preserveRoute) window.history.pushState({ supportTicket: ticket._id }, "", `${window.location.pathname}${window.location.search}#/support/${accountType.toLowerCase()}/tickets/${ticket._id}`); window.scrollTo(0, 0); };
  const closeTicket = () => { setSelected(null); if (!preserveRoute) window.history.back(); };
  const submit = async (event) => { event.preventDefault(); setBusy(true); try { const ticket = await createTicket(form); setForm({ subject: "", category: "general", orderId: "", priority: "normal", message: "" }); setOpen(false); setMessage(`${ticket.ticketNumber} created successfully.`); await load(); openTicket(ticket); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const sendReply = async (event) => { event.preventDefault(); if (!reply.trim()) return; setBusy(true); try { const ticket = await replyTicket(selected._id, reply.trim()); setReply(""); setSelected(ticket); await load(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };

  if (selected) return <section className="ticketDetailRoute"><section className="ticketConversation"><div className="panelHeader"><div><span className="eyebrow">{selected.ticketNumber}</span><h2>{selected.subject}</h2><p>{selected.status} · {selected.assignedStaff?.name || "Admin Queue"}</p></div><button className="inlineButton" onClick={closeTicket}><X size={16}/> Back to tickets</button></div><div className="ticketMessages">{selected.messages.map((entry) => <article key={entry._id} className={entry.authorType === "User" ? "staff" : "requester"}><strong>{entry.authorName || entry.authorType}</strong><p>{entry.message}</p><small>{new Date(entry.createdAt).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</small></article>)}</div>{!["Resolved", "Closed"].includes(selected.status) && <form className="ticketReply" onSubmit={sendReply}><MessageSquareText/><textarea required value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Write a reply…"/><button className="primaryButton" disabled={busy}>{busy ? "Sending…" : "Send reply"}</button></form>}</section></section>;

  return <section className="supportTicketPage"><div className="sellerKycHeading"><div><span className="eyebrow">Help &amp; Support</span><h2>Support Tickets</h2><p>Create a general ticket or link your issue to an order.</p></div><button className="primaryButton" onClick={() => setOpen(true)}><Plus size={17}/> New Ticket</button></div>{message && <div className="notice">{message}</div>}<div className="panel tableWrap"><table><thead><tr><th>Ticket</th><th>Subject</th><th>Category</th><th>Order</th><th>Assigned to</th><th>Status</th><th>Updated</th></tr></thead><tbody>{tickets.map((ticket) => <tr className="clickableTableRow" key={ticket._id} onClick={() => openTicket(ticket)}><td><strong>{ticket.ticketNumber}</strong></td><td>{ticket.subject}</td><td>{ticket.category}</td><td>{ticket.order?.orderNumber || "General"}</td><td>{ticket.assignedStaff?.name || "Admin Queue"}</td><td><span className={`ticketStatus ${ticket.status.toLowerCase().replaceAll(" ", "-")}`}>{ticket.status}</span></td><td>{new Date(ticket.lastActivityAt).toLocaleString("en-IN")}</td></tr>)}{!tickets.length && <tr><td colSpan="7">No support tickets yet.</td></tr>}</tbody></table></div>
    {open && <div className="modalOverlay"><form className="sellerStatusModal" onSubmit={submit}><div className="panelHeader"><div><span className="eyebrow">New support request</span><h2>Create Ticket</h2></div><button type="button" className="inlineButton" onClick={() => setOpen(false)}><X size={16}/> Close</button></div><label>Subject<input required value={form.subject} onChange={(event) => setForm({ ...form, subject: event.target.value })}/></label><label>Issue type<select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value, orderId: event.target.value === "order" ? form.orderId : "" })}>{["general", "order", "payment", "return", "kyc", "product", "payout", "account", "other"].filter((item) => !preserveRoute || item !== "order" || orders.length > 0).map((item) => <option key={item}>{item}</option>)}</select></label>{form.category === "order" && <label>Related order<select required value={form.orderId} onChange={(event) => setForm({ ...form, orderId: event.target.value })}><option value="">Select order</option>{orders.map((order) => <option key={order._id} value={order._id}>{order.orderNumber}</option>)}</select></label>}<label>Priority<select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}>{["low", "normal", "high", "urgent"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Issue details<textarea required rows="5" value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })}/></label><button className="primaryButton" disabled={busy}>{busy ? "Creating…" : "Create Ticket"}</button></form></div>}
  </section>;
}
