import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { useAuth } from "@/context/AuthContext";
import { colors } from "@/theme";
const links:[string,keyof typeof Ionicons.glyphMap,string][]=[["Home","home-outline","/(tabs)"],["Shop all","grid-outline","/(tabs)/shop"],["Categories","albums-outline","/categories"],["Wishlist","heart-outline","/wishlist"],["My orders","cube-outline","/orders"],["My account","person-outline","/(tabs)/account"],["Contact us","chatbubble-outline","/contact"]];
export function AppDrawer({visible,onClose}:{visible:boolean;onClose:()=>void}){const{customer,logout}=useAuth();const go=(href:string)=>{onClose();router.push(href as any)};return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={s.modal}><Pressable style={s.scrim} onPress={onClose}/><View style={s.drawer}><View style={s.top}><View style={s.logo}><Ionicons name="basket" size={25} color="white"/></View><View style={{flex:1}}><Text style={s.brand}>HRS Basket</Text><Text style={s.hello}>{customer?`Hello, ${customer.name.split(" ")[0]}`:"Welcome to our shop"}</Text></View><Pressable onPress={onClose}><Ionicons name="close" size={25}/></Pressable></View><View style={s.links}>{links.map(([label,icon,href])=><Pressable key={label} onPress={()=>go(href)} style={s.link}><Ionicons name={icon} size={21} color={colors.primary}/><Text style={s.text}>{label}</Text><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Pressable>)}</View><View style={s.bottom}>{customer?<Pressable onPress={async()=>{await logout();onClose();router.replace("/(tabs)/account")}} style={s.logout}><Ionicons name="log-out-outline" size={20} color={colors.danger}/><Text style={{color:colors.danger,fontWeight:"700"}}>Sign out</Text></Pressable>:<Pressable onPress={()=>go("/login")} style={s.signin}><Text style={{color:"white",fontWeight:"800"}}>Sign in / Create account</Text></Pressable>}</View></View></View></Modal>}
const s=StyleSheet.create({modal:{flex:1,flexDirection:"row"},scrim:{...StyleSheet.absoluteFillObject,backgroundColor:"rgba(13,27,20,.45)"},drawer:{width:"84%",maxWidth:360,height:"100%",backgroundColor:"white",paddingTop:54},top:{paddingHorizontal:20,paddingBottom:20,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderColor:colors.line},logo:{width:44,height:44,borderRadius:13,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center"},brand:{fontWeight:"900",fontSize:19,color:colors.primaryDark},hello:{fontSize:12,color:colors.muted,marginTop:2},links:{padding:12},link:{height:52,flexDirection:"row",alignItems:"center",gap:14,paddingHorizontal:10,borderRadius:12},text:{flex:1,fontSize:15,fontWeight:"600",color:colors.ink},bottom:{marginTop:"auto",padding:20,borderTopWidth:1,borderColor:colors.line},signin:{height:48,backgroundColor:colors.primary,borderRadius:13,alignItems:"center",justifyContent:"center"},logout:{height:48,flexDirection:"row",gap:10,alignItems:"center",justifyContent:"center",backgroundColor:"#fff1f1",borderRadius:13}});

