import { Ionicons } from "@expo/vector-icons";
import { PropsWithChildren } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, TextInputProps, View } from "react-native";
import { colors, radius } from "@/theme";

export function Button({title,onPress,loading=false,variant="primary",disabled=false,icon}:{title:string;onPress:()=>void;loading?:boolean;variant?:"primary"|"outline"|"ghost";disabled?:boolean;icon?:keyof typeof Ionicons.glyphMap}){return <Pressable disabled={disabled||loading} onPress={onPress} style={({pressed})=>[s.button,variant==="outline"&&s.outline,variant==="ghost"&&s.ghost,(pressed||disabled)&&{opacity:.65}]}>{loading?<ActivityIndicator color={variant==="primary"?"white":colors.primary}/>:<>{icon&&<Ionicons name={icon} size={18} color={variant==="primary"?"white":colors.primary}/>}<Text style={[s.buttonText,variant!=="primary"&&{color:colors.primary}]}>{title}</Text></>}</Pressable>}
export function Field({label,error,...props}:TextInputProps&{label?:string;error?:string}){return <View style={{gap:6}}>{label&&<Text style={s.label}>{label}</Text>}<TextInput placeholderTextColor="#95a19b" {...props} style={[s.field,props.multiline&&{height:96,textAlignVertical:"top"},props.style]}/>{error&&<Text style={s.error}>{error}</Text>}</View>}
export function EmptyState({icon="basket-outline",title,message,action}:{icon?:keyof typeof Ionicons.glyphMap;title:string;message:string;action?:React.ReactNode}){return <View style={s.empty}><View style={s.emptyIcon}><Ionicons name={icon} size={34} color={colors.primary}/></View><Text style={s.emptyTitle}>{title}</Text><Text style={s.emptyMessage}>{message}</Text>{action}</View>}
export function SectionTitle({title,action,onAction}: {title:string;action?:string;onAction?:()=>void}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{action&&<Pressable onPress={onAction}><Text style={s.action}>{action}  ›</Text></Pressable>}</View>}
export function Chip({label,selected,onPress}:{label:string;selected?:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.chip,selected&&s.chipOn]}><Text style={[s.chipText,selected&&{color:"white"}]}>{label}</Text></Pressable>}
export function Card({children,style}:PropsWithChildren<{style?:any}>){return <View style={[s.card,style]}>{children}</View>}
const s=StyleSheet.create({button:{height:50,borderRadius:14,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:8,paddingHorizontal:18},outline:{backgroundColor:"white",borderWidth:1,borderColor:colors.primary},ghost:{backgroundColor:colors.primarySoft},buttonText:{color:"white",fontSize:15,fontWeight:"700"},label:{fontSize:13,fontWeight:"700",color:colors.ink},field:{height:50,borderWidth:1,borderColor:colors.line,borderRadius:12,backgroundColor:"white",paddingHorizontal:14,fontSize:15,color:colors.ink},error:{fontSize:12,color:colors.danger},empty:{alignItems:"center",padding:36,gap:10},emptyIcon:{width:70,height:70,borderRadius:35,backgroundColor:colors.primarySoft,alignItems:"center",justifyContent:"center"},emptyTitle:{fontSize:20,fontWeight:"800",color:colors.ink},emptyMessage:{color:colors.muted,textAlign:"center",lineHeight:21,marginBottom:8},section:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:14},sectionTitle:{fontSize:21,fontWeight:"800",color:colors.ink},action:{color:colors.primary,fontWeight:"700"},chip:{paddingHorizontal:16,height:38,borderRadius:19,borderWidth:1,borderColor:colors.line,justifyContent:"center",backgroundColor:"white"},chipOn:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{color:colors.ink,fontWeight:"600"},card:{backgroundColor:"white",borderRadius:radius.md,borderWidth:1,borderColor:colors.line,overflow:"hidden"}});
