import { router,useLocalSearchParams } from 'expo-router';
import { useEffect,useState } from 'react';
import { ActivityIndicator,Image,Pressable,ScrollView,StyleSheet,Text,View,useWindowDimensions } from 'react-native';
import { Screen } from '@/components/Screen';
import { Button,Chip,Field } from '@/components/Ui';
import { ContentSections, ProductGrid } from '@/components/HomeContent';
import { RichContent } from '@/components/RichContent';
import { Video } from '@/components/Video';
import { useShop } from '@/context/ShopContext';
import { useAuth } from '@/context/AuthContext';
import { api,mediaUrl } from '@/lib/api';
import { availableStock,matchesCategory,money,productPrice } from '@/lib/commerce';
import { colors } from '@/theme';
import type { Product,Variant } from '@/types';
export default function ProductDetail(){
 const {id}=useLocalSearchParams<{id:string}>();const {store,addToCart,wishlist,toggleWishlist}=useShop();const {customer}=useAuth();const {width}=useWindowDimensions();const tablet=width>=768;const imageWidth=tablet?Math.min(width,1200)*.45:width-32;
 const [product,setProduct]=useState<Product>();const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [selected,setSelected]=useState<Variant>();const [reviews,setReviews]=useState<any[]>([]);const [rating,setRating]=useState(5);const [comment,setComment]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const load=()=>{setLoading(true);setError('');Promise.all([api.product(id),api.reviews(id)]).then(([p,r])=>{setProduct(p);setReviews(Array.isArray(r)?r:r.items||[]);setSelected(undefined)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(load,[id]);
 const review=async()=>{if(!customer){router.push('/login');return;}setBusy(true);try{const r=await api.createReview(id,{rating,sellerRating:rating,comment});setMessage(r.message||'Review submitted for approval');setComment('')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 if(loading)return <Screen title="Product" back><ActivityIndicator style={{marginTop:60}}/></Screen>;if(error||!product)return <Screen title="Product" back><View style={{padding:24,gap:12}}><Text>{error||'Product unavailable'}</Text><Button title="Retry" onPress={load}/></View></Screen>;
 const stock=availableStock(product,selected);const liked=wishlist.some(p=>p._id===id);const images=[product.mainImage,...(product.media||[]).filter(m=>m.type==='image').map(m=>m.url)].filter(Boolean) as string[];
 return <Screen title={product.name} back><ScrollView contentContainerStyle={s.content}><View style={[s.layout,tablet&&{flexDirection:'row'}]}><View style={{width:imageWidth,gap:12}}><ScrollView horizontal pagingEnabled showsHorizontalScrollIndicator={false}>{[...new Set(images)].map(url=><Image key={url} source={{uri:mediaUrl(url)}} style={{width:imageWidth,height:imageWidth,borderRadius:20}} resizeMode="contain"/>)}</ScrollView>{product.videoUrl&&<Video url={product.videoUrl}/>}</View><View style={s.details}><View style={s.row}><Text style={s.brand}>{product.manufacturerBrand}</Text><Pressable accessibilityLabel="Save product" onPress={()=>toggleWishlist(product)}><Text style={{fontSize:27,color:liked?colors.danger:colors.primary}}>{liked?'♥':'♡'}</Text></Pressable></View><Text style={s.title}>{product.name}</Text><Text>★ {product.averageRating||0} · {reviews.length} reviews</Text><Text style={s.price}>{money(productPrice(product,selected))}</Text><Text style={s.muted}>Inclusive of all taxes</Text>{product.variants?.length&&<><Text style={s.label}>Choose an option</Text><View style={s.options}>{product.variants.map((v,i)=><Chip key={v.sku||i} label={v.name||Object.values(v.attributes||{}).join(' / ')||v.sku||`Option ${i+1}`} selected={selected===v} onPress={()=>setSelected(v)}/>)}</View></>}<Text style={{color:stock>0?colors.success:colors.danger,fontWeight:'700'}}>{stock>0?'Available':'Out of stock'}</Text><Button title="Add to cart" disabled={stock===0} onPress={()=>{if(addToCart(product,selected))setMessage('Added to cart')}}/><Button title="Buy now" disabled={stock===0} variant="outline" onPress={()=>{if(addToCart(product,selected))router.push('/checkout')}}/>{product.seller&&<Pressable onPress={()=>router.push({pathname:'/seller/[id]',params:{id:product.seller!._id}})}><Text style={s.brand}>Sold by {product.seller.companyName} ›</Text></Pressable>}<Text style={s.muted}>{product.isReturnable===false?'This product is not returnable':`${product.returnDays??7}-day return policy`}</Text>{store.settings.productAssurances&&<Text style={s.muted}>{Object.values(store.settings.productAssurances).join(' · ')}</Text>}</View></View>
 <Text style={s.heading}>Product details</Text><RichContent html={product.detailedDescription||product.description||product.shortDescription||''}/><ContentSections sections={(store.contentSections||[]).filter(s=>s.locations?.includes('product_detail_below_details'))}/>
 <Text style={s.heading}>Customer reviews</Text>{reviews.map(r=><View key={r._id} style={s.review}><Text style={s.label}>{r.name} · {r.rating}/5</Text><Text style={s.muted}>{r.comment}</Text></View>)}{!reviews.length&&<Text style={s.muted}>No approved reviews yet.</Text>}<Text style={s.label}>Review your purchase</Text><View style={s.options}>{[1,2,3,4,5].map(n=><Chip key={n} label={`${n} ★`} selected={rating===n} onPress={()=>setRating(n)}/>)}</View><Field value={comment} onChangeText={setComment} placeholder="Share your experience" multiline maxLength={2000}/><Button title={customer?'Submit review':'Sign in to review'} loading={busy} onPress={review}/>{message&&<Text style={s.brand}>{message}</Text>}
 <Text style={s.heading}>You may also like</Text><ProductGrid products={store.products.filter(p=>p._id!==id&&p.displayType!=='Reel'&&matchesCategory(p,typeof product.category==='string'?product.category:product.category?._id||'all')).slice(0,4)} columns={tablet?4:2}/>
 </ScrollView></Screen>;
}
const s=StyleSheet.create({content:{padding:16,gap:18,paddingBottom:40},layout:{gap:22},details:{flex:1,gap:13},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},brand:{color:colors.primary,fontWeight:'800'},title:{fontSize:28,fontWeight:'900',color:colors.ink},price:{fontSize:28,fontWeight:'900'},muted:{color:colors.muted,lineHeight:23},label:{fontWeight:'800',color:colors.ink},options:{flexDirection:'row',flexWrap:'wrap',gap:8},heading:{fontSize:22,fontWeight:'900',color:colors.ink,marginTop:10},review:{backgroundColor:'white',padding:16,borderRadius:14,gap:8}});
