import SupportTicket from "../models/SupportTicket.js";
import Sequence from "../models/Sequence.js";
import WorkAssignment from "../models/WorkAssignment.js";
import StaffTeam from "../models/StaffTeam.js";
import Order from "../models/Order.js";
import StaffAuditLog from "../models/StaffAuditLog.js";
import asyncHandler from "../utils/asyncHandler.js";

const prefixes = { Customer: "C", Seller: "S", Partner: "P" };
const nextTicketNumber = async (type) => { const year = new Date().getFullYear(); const row = await Sequence.findOneAndUpdate({ key: `ticket-${type}-${year}` }, { $inc: { value: 1 } }, { upsert: true, new: true }); return `${prefixes[type]}-${year}-${String(row.value).padStart(6, "0")}`; };
const requesterFrom = (req, type) => type === "Customer" ? req.customer : type === "Seller" ? req.seller : req.partner;
const populateTicket = (query) => query.populate("requester", "name companyName sellerNumber registrationNumber email mobile phone").populate("order", "orderNumber status grandTotal").populate("assignedTeam", "name code").populate("assignedTeamLeader assignedStaff", "name employeeCode role email");
const ticketScope = (user) => user.role === "Super Admin" ? {} : user.role === "Team Leader" ? { assignedTeamLeader: user._id } : { assignedStaff: user._id };

const createFor = (type) => asyncHandler(async (req, res) => {
  const requester = requesterFrom(req, type); const subject = String(req.body.subject || "").trim(); const message = String(req.body.message || "").trim();
  if (!subject || !message) { res.status(400); throw new Error("Subject and issue details are required"); }
  let order;
  if (req.body.orderId) { order = await Order.findById(req.body.orderId); const owns = type === "Customer" ? String(order?.customer) === String(requester._id) : type === "Seller" ? order?.items?.some((item) => String(item.seller) === String(requester._id)) : false; if (!order || !owns) { res.status(403); throw new Error("Selected order is not available for this account"); } }
  const assignment = await WorkAssignment.findOne({ entityType: type, entity: requester._id, action: { $in: ["support", "customer_care"] }, active: true, staff: { $exists: true, $ne: null } }).sort({ updatedAt: -1 }).populate("team");
  const ticketNumber = await nextTicketNumber(type); const assigned = Boolean(assignment?.staff);
  const ticket = await SupportTicket.create({ ticketNumber, requesterType: type, requester: requester._id, subject, category: req.body.orderId ? "order" : req.body.category || "general", order: order?._id, priority: req.body.priority || "normal", status: assigned ? "Assigned" : "Open", assignedTeam: assignment?.team?._id, assignedTeamLeader: assignment?.teamLeader, assignedStaff: assignment?.staff, routedToAdmin: !assigned, messages: [{ authorType: type, author: requester._id, authorName: requester.name || requester.companyName, message, attachments: req.body.attachments || [] }], history: [{ action: "created", to: assigned ? "Assigned Staff" : "Admin Queue", note: assigned ? `Automatically routed using ${assignment.action} assignment` : "No active staff assignment; forwarded to Admin", actorType: type, actor: requester._id, actorName: requester.name || requester.companyName }] });
  res.status(201).json(await populateTicket(SupportTicket.findById(ticket._id)));
});
export const createCustomerTicket = createFor("Customer"); export const createSellerTicket = createFor("Seller"); export const createPartnerTicket = createFor("Partner");
const ownList = (type) => asyncHandler(async (req, res) => { const account = requesterFrom(req, type); res.json(await populateTicket(SupportTicket.find({ requesterType: type, requester: account._id }).sort({ lastActivityAt: -1 }))); });
export const customerTickets = ownList("Customer"); export const sellerTickets = ownList("Seller"); export const partnerTickets = ownList("Partner");
export const listAdminTickets = asyncHandler(async (req, res) => { const query = ticketScope(req.user); if (req.query.status && req.query.status !== "All") query.status = req.query.status; if (req.query.requesterType && req.query.requesterType !== "All") query.requesterType = req.query.requesterType; res.json(await populateTicket(SupportTicket.find(query).sort({ lastActivityAt: -1 }).limit(500))); });
export const getAdminTicket = asyncHandler(async (req, res) => { const ticket = await populateTicket(SupportTicket.findOne({ _id: req.params.id, ...ticketScope(req.user) })); if (!ticket) { res.status(404); throw new Error("Ticket not found in your assignment scope"); } res.json(ticket); });
export const replyAsRequester = (type) => asyncHandler(async (req, res) => { const requester = requesterFrom(req, type); const ticket = await SupportTicket.findOne({ _id: req.params.id, requesterType: type, requester: requester._id }); if (!ticket) { res.status(404); throw new Error("Ticket not found"); } const message = String(req.body.message || "").trim(); if (!message) { res.status(400); throw new Error("Message is required"); } ticket.messages.push({ authorType: type, author: requester._id, authorName: requester.name || requester.companyName, message }); ticket.history.push({ action: "requester_reply", actorType: type, actor: requester._id, actorName: requester.name || requester.companyName }); ticket.lastActivityAt = new Date(); if (ticket.status === "Waiting for Customer") ticket.status = ticket.assignedStaff ? "In Progress" : "Open"; await ticket.save(); res.json(await populateTicket(SupportTicket.findById(ticket._id))); });
export const customerTicketReply = replyAsRequester("Customer"); export const sellerTicketReply = replyAsRequester("Seller"); export const partnerTicketReply = replyAsRequester("Partner");
export const updateTicket = asyncHandler(async (req, res) => { const ticket = await SupportTicket.findOne({ _id: req.params.id, ...ticketScope(req.user) }); if (!ticket) { res.status(404); throw new Error("Ticket not found in your assignment scope"); } const before = { status: ticket.status, assignedStaff: ticket.assignedStaff, assignedTeam: ticket.assignedTeam };
  if (req.body.team || req.body.staff) { if (req.user.role !== "Super Admin" && req.user.role !== "Team Leader") { res.status(403); throw new Error("Only Admin or Team Leader can reassign tickets"); } const team = await StaffTeam.findById(req.body.team || ticket.assignedTeam); if (!team || (req.user.role === "Team Leader" && String(team.leader) !== String(req.user._id))) { res.status(403); throw new Error("Ticket can only be assigned within your team"); } if (req.body.staff && !team.members.some((id) => String(id) === String(req.body.staff))) { res.status(400); throw new Error("Staff member is not in this team"); } ticket.assignedTeam = team._id; ticket.assignedTeamLeader = team.leader; ticket.assignedStaff = req.body.staff || undefined; ticket.routedToAdmin = false; ticket.status = req.body.staff ? "Assigned" : ticket.status; }
  if (req.body.status) { if (!["Open", "Assigned", "In Progress", "Waiting for Customer", "Resolved", "Closed"].includes(req.body.status)) { res.status(400); throw new Error("Invalid ticket status"); } ticket.status = req.body.status; if (req.body.status === "Resolved") ticket.resolvedAt = new Date(); if (req.body.status === "Closed") ticket.closedAt = new Date(); }
  const message = String(req.body.message || "").trim(); if (message) ticket.messages.push({ authorType: "User", author: req.user._id, authorName: req.user.name, message }); ticket.history.push({ action: "staff_update", from: before.status, to: ticket.status, note: message || req.body.note, actorType: "User", actor: req.user._id, actorName: req.user.name }); ticket.lastActivityAt = new Date(); await ticket.save();
  await StaffAuditLog.create({ actor: req.user._id, actorName: req.user.name, actorRole: req.user.role, entityType: ticket.requesterType, entity: ticket.requester, action: "ticket_updated", description: `${ticket.ticketNumber} updated`, changes: { before, status: ticket.status, assignedStaff: ticket.assignedStaff }, request: { method: req.method, path: req.originalUrl, ip: req.ip } }); res.json(await populateTicket(SupportTicket.findById(ticket._id))); });
