import ProfileSummary from "../ProfileSummary.jsx";
import { useState } from "react";
import { api } from "../../services/api.js";
export default function ResellerBankProfile({ account, onSaved, setStatus }) {
  const saved = account.paymentDetails || {}; const [form, setForm] = useState({ upiId: saved.upiId || "", upiDisplayName: saved.upiDisplayName || "", accountHolder: saved.accountHolder || "", accountNumber: saved.accountNumber || "", ifsc: saved.ifsc || "", bankName: saved.bankName || "", branch: saved.branch || "" }); const [busy, setBusy] = useState(false);
  const changeIfsc = async (value) => { const ifsc = value.toUpperCase().replace(/\s/g, "").slice(0, 11); setForm(current => ({ ...current, ifsc, bankName: "", branch: "" })); if (ifsc.length !== 11) return; setBusy(true); try { const bank = await api.resellerLookupIfsc(ifsc); setForm(current => ({ ...current, ...bank })); } catch (error) { setStatus(error.message); } finally { setBusy(false); } };
  const save = async (event) => { event.preventDefault(); setBusy(true); try { const updated = await api.updateResellerBank(form); onSaved(updated); setStatus("Bank details verified and saved."); } catch (error) { setStatus(error.message); } finally { setBusy(false); } };
  const saveUpi = async () => { setBusy(true); try { const updated = await api.updateResellerBank({ upiId: form.upiId, upiDisplayName: form.upiDisplayName }); onSaved(updated); setStatus("UPI details updated."); } catch (error) { setStatus(error.message); } finally { setBusy(false); } };
  return <section><ProfileSummary account={account} role="Reseller" note="Your saved bank details are used for wallet withdrawals. Keep your account holder name and payment details up to date." /><h3 className="resellerBankSectionHeading">Bank &amp; Payment Details</h3><form className="resellerPanel resellerBankForm" onSubmit={save}><label>Account holder name<input required value={form.accountHolder} onChange={(e) => setForm({ ...form, accountHolder: e.target.value })} /></label><label>Account number<input required inputMode="numeric" pattern="[0-9]{6,20}" value={form.accountNumber} onChange={(e) => setForm({ ...form, accountNumber: e.target.value.replace(/\D/g, "") })} /></label><label>IFSC<input required maxLength="11" value={form.ifsc} onChange={(e) => changeIfsc(e.target.value)} /><small>{busy ? "Finding bank and branch…" : "Bank details are fetched automatically."}</small></label><label>Bank name<input readOnly required value={form.bankName} /></label><label>Branch<input readOnly required value={form.branch} /></label>{[["upiId", "UPI ID"], ["upiDisplayName", "UPI display name"]].map(([field, label]) => <label key={field}>{label}<input value={form[field] || ""} onChange={e => setForm({ ...form, [field]: e.target.value })} /></label>)}<button type="button" className="resellerPrimary" disabled={busy} onClick={saveUpi}>Save UPI details</button><button className="resellerPrimary" disabled={busy || !form.bankName || !form.branch}>{busy ? "Please wait…" : "Save bank details"}</button></form></section>;
}
