import { ArrowLeft, ShoppingBag, UserPlus, User, Smartphone, Mail, LockKeyhole, EyeOff, Eye, Store, ShieldCheck, FileText, Building2, MapPin, Check } from "lucide-react";
import { strongPasswordPattern } from "./portalUtils.js";
import { api } from "../../services/api.js";
export default function ResellerQuickRegistration({ setPortalRoute, branding, status, submitQuickRegistration, quickForm, setQuickForm, showAccessPassword, setShowAccessPassword, setQuickGstVerification, quickGstVerification, verifyQuickGstin, quickCertificate, setQuickCertificate, accessBusy }) {
  return (<main className="resellerQuickRegistration resellerRegistrationPage">
    <section className="resellerRegistrationHero">
      <button className="resellerBackButton" type="button" onClick={() => { window.location.hash = "#/reseller"; setPortalRoute("#/reseller") }} aria-label="Back to reseller login"><ArrowLeft size={19} /></button>
      <strong className="resellerBrandText">{branding.logoUrl ? <img src={branding.logoUrl} alt="HRSBasket" className="resellerBrandLogo" /> : <ShoppingBag />}</strong>
      <div className="resellerHeroCopy"><span className="resellerHeroIcon"><UserPlus /></span><div><h1><em>Reseller</em> Registration</h1><p>Join HRSBasket and start earning by sharing products with your network.</p></div></div>
      <div className="resellerHeroArt" aria-hidden="true"><span>₹</span><UserPlus /><i>↗</i></div>
    </section>
    <section className="resellerRegistrationCard resellerQuickCard">
      <div className="resellerFormHeading"><h2>Quick reseller registration</h2></div>
      {status && <p className="resellerNotice" role="alert">{status}</p>}
      <form className="resellerForm" onSubmit={submitQuickRegistration}>
        <label className="resellerField resellerFullField"><span>Full name <b>*</b></span><div><User /><input required placeholder="Enter your full name" value={quickForm.fullName} onChange={e => setQuickForm({ ...quickForm, fullName: e.target.value })} /></div></label>
        <label className="resellerField resellerFullField"><span>Mobile number <b>*</b></span><div><Smartphone /><span className="resellerDialCode">+91</span><input required inputMode="numeric" pattern="[0-9]{10}" maxLength="10" placeholder="Enter mobile number" value={quickForm.mobile} onChange={e => setQuickForm({ ...quickForm, mobile: e.target.value.replace(/\D/g, "").slice(0, 10) })} /></div></label>
        <label className="resellerField resellerFullField"><span>Email address <b>*</b></span><div><Mail /><input required type="email" placeholder="Enter email address" value={quickForm.email} onChange={e => setQuickForm({ ...quickForm, email: e.target.value })} /></div></label>
        <label className="resellerField resellerFullField"><span>Create password <b>*</b></span><div><LockKeyhole /><input required minLength="8" type={showAccessPassword ? "text" : "password"} placeholder="Create a strong password" value={quickForm.password} onChange={e => setQuickForm({ ...quickForm, password: e.target.value })} /><button className="resellerQuickEye" type="button" onClick={() => setShowAccessPassword(!showAccessPassword)} aria-label="Show or hide passwords">{showAccessPassword ? <EyeOff /> : <Eye />}</button></div><small className={quickForm.password && !strongPasswordPattern.test(quickForm.password) ? "resellerPasswordHint invalid" : "resellerPasswordHint"}>Minimum 8 characters with uppercase, lowercase, number and special character.</small></label>
        <label className="resellerField resellerFullField"><span>Confirm password <b>*</b></span><div><LockKeyhole /><input required minLength="8" type={showAccessPassword ? "text" : "password"} placeholder="Enter password again" value={quickForm.confirmPassword} onChange={e => setQuickForm({ ...quickForm, confirmPassword: e.target.value })} /></div>{quickForm.confirmPassword && <small className={`resellerPasswordHint ${quickForm.password === quickForm.confirmPassword ? "matches" : "invalid"}`}>{quickForm.password === quickForm.confirmPassword ? "Passwords match." : "Passwords do not match."}</small>}</label>
        <label className="resellerField resellerFullField"><span>Business / shop name <b>*</b></span><div><Store /><input required readOnly={quickForm.gstStatus === "gst" && Boolean(quickForm.taxVerificationToken)} placeholder="Enter business or shop name" value={quickForm.businessName} onChange={e => setQuickForm({ ...quickForm, businessName: e.target.value })} /></div></label>
        <fieldset className="resellerGstField"><legend>GST status <b>*</b></legend><div className="resellerGstChoices"><label className={quickForm.gstStatus === "gst" ? "selected" : ""}><input type="radio" checked={quickForm.gstStatus === "gst"} onChange={() => setQuickForm({ ...quickForm, gstStatus: "gst" })} /><ShieldCheck /><span><strong>GST Registered</strong><small>I have GSTIN</small></span></label><label className={quickForm.gstStatus === "non-gst" ? "selected" : ""}><input type="radio" checked={quickForm.gstStatus === "non-gst"} onChange={() => setQuickForm({ ...quickForm, gstStatus: "non-gst" })} /><FileText /><span><strong>Non-GST</strong><small>I don’t have GSTIN</small></span></label></div></fieldset>
        {quickForm.gstStatus === "gst" && <section className="resellerQuickGst resellerFullField">
          <label className="resellerField"><span>GSTIN <b>*</b></span><div><Building2 /><input required maxLength="15" placeholder="Enter 15-digit GSTIN" value={quickForm.gstin} onChange={e => { setQuickForm({ ...quickForm, gstin: e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 15), taxVerificationToken: "", gstState: "", gstCertificate: "" }); setQuickGstVerification({ busy: false, status: "", message: "" }) }} /><button className="resellerInlineVerify" type="button" disabled={quickGstVerification.busy || quickForm.gstin.length !== 15} onClick={verifyQuickGstin}>{quickGstVerification.busy ? "Verifying…" : "Verify"}</button></div></label>
          <label className="resellerField"><span>Registered state</span><div><MapPin /><input readOnly placeholder="Filled after GST verification" value={quickForm.gstState} /></div></label>
          {quickGstVerification.message && <p className={`resellerGstMessage ${quickGstVerification.status}`} role="status">{quickGstVerification.message}</p>}
          <label className="resellerField resellerFullField"><span>GST certificate <b>*</b></span><div className="resellerFileInput"><FileText /><input required={!quickForm.gstCertificate} type="file" accept="image/*,.pdf" disabled={!quickForm.taxVerificationToken || quickCertificate.busy} onChange={async e => { const file = e.target.files?.[0]; if (!file) return; setQuickCertificate({ busy: true, name: file.name, error: "" }); try { const uploaded = await api.uploadSellerRegistrationDocument(file); if (!uploaded?.url) throw new Error("The upload completed without a document URL."); setQuickForm(current => ({ ...current, gstCertificate: uploaded.url })); setQuickCertificate({ busy: false, name: file.name, error: "" }) } catch (error) { e.target.value = ""; setQuickCertificate({ busy: false, name: "", error: error.message }) } }} /></div>{quickCertificate.busy && <small>Uploading {quickCertificate.name}…</small>}{quickCertificate.error && <small className="errorText">{quickCertificate.error}</small>}{quickForm.gstCertificate && <small className="resellerUploadSuccess"><Check /> Certificate uploaded: {quickCertificate.name}</small>}</label>
        </section>}
        <label className="resellerTerms resellerFullField"><input required type="checkbox" checked={quickForm.termsAccepted} onChange={e => setQuickForm({ ...quickForm, termsAccepted: e.target.checked })} /><span>I accept the <a href="#/terms">Terms &amp; Conditions</a> and <a href="#/privacy">Privacy Policy</a> <b>*</b></span></label>
        <aside className="resellerInfoNote resellerFullField"><strong>★ More information</strong> (additional address, bank details, PAN, etc.) will be required in your profile after registration to activate your account.</aside>
        <button className="resellerSubmit resellerFullField" disabled={accessBusy || quickCertificate.busy || (quickForm.gstStatus === "gst" && (!quickForm.taxVerificationToken || !quickForm.gstCertificate))}><UserPlus />{accessBusy ? "Registering…" : "Register as Reseller"}</button>
        <p className="resellerLoginPrompt resellerFullField">Already have an account? <button type="button" onClick={() => { window.location.hash = "#/reseller"; setPortalRoute("#/reseller") }}>Login Here</button></p>
      </form>
    </section>
  </main>);
}
