import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, Eye, EyeOff, FileText, LockKeyhole, Mail, MapPin, ShieldCheck, ShoppingBag, Smartphone, Store, User, UserPlus } from "lucide-react";
import { strongPasswordPattern } from "./portalUtils.js";
import { api } from "../../services/api.js";

const steps = ["Basic details", "Account security", "GST details", "Business details"];

export default function ResellerQuickRegistration({ setPortalRoute, branding = {}, status, submitQuickRegistration, quickForm, setQuickForm, showAccessPassword, setShowAccessPassword, setQuickGstVerification, quickGstVerification, verifyQuickGstin, quickCertificate, setQuickCertificate, accessBusy, registrationResult, onLogin }) {
  const [screen, setScreen] = useState("welcome");
  const [step, setStep] = useState(1);
  const update = patch => setQuickForm(current => ({ ...current, ...patch }));
  const back = () => step > 1 ? setStep(step - 1) : setScreen("welcome");
  const continueStep = event => { event.preventDefault(); if (event.currentTarget.reportValidity()) setStep(current => Math.min(4, current + 1)); };
  if (registrationResult) return <main className="resellerWizardPage resellerWizardSuccess"><section className="resellerSuccessCard">{branding.logoUrl && <img className="resellerAdminLogo" src={branding.logoUrl} alt={branding.shopName || "HRSBasket"} />}<span className="resellerSuccessCheck"><Check /></span><h1>Registration <em>Successful!</em></h1><p>Your reseller account has been created successfully. You can now login and start sharing products.</p><div><User /><span>Your Reseller ID<strong>{registrationResult.reseller?.resellerId}</strong></span></div><button type="button" onClick={onLogin}>Go to Login <ArrowRight /></button><small>Welcome to the Reseller Community!</small><Store className="resellerSuccessStore" /></section></main>;
  if (screen === "welcome") return <main className="resellerWizardPage"><section className="resellerWelcomeCard"><button className="resellerWizardBack" type="button" onClick={() => { window.location.hash = "#/reseller"; setPortalRoute("#/reseller"); }}><ArrowLeft /></button>{branding.logoUrl && <img className="resellerWizardLogo" src={branding.logoUrl} alt="HRSBasket" />}<div className="resellerWelcomeTitle"><span>Become a</span><h1>Reseller</h1><strong>Register Now</strong></div><p>Grow Your Business<br />With Us</p><div className="resellerWelcomeBenefits"><span><ShieldCheck />No Investment</span><span><Store />Create Your Own Store</span><span><ShoppingBag />Share Products &amp; Earn</span><span><UserPlus />Flexible Earning Option</span></div><h2>Simple Steps,<br />Big Opportunities!</h2><button className="resellerWizardPrimary" type="button" onClick={() => setScreen("form")}>Start Registration <ArrowRight /></button></section></main>;
  return <main className="resellerWizardPage"><section className="resellerWizardCard">
    <button className="resellerWizardBack" type="button" onClick={back}><ArrowLeft /></button>
    {branding.logoUrl && <img className="resellerAdminLogo" src={branding.logoUrl} alt={branding.shopName || "HRSBasket"} />}
    <ol className="resellerWizardProgress">{steps.map((label, index) => <li className={step === index + 1 ? "active" : step > index + 1 ? "complete" : ""} key={label}><span>{step > index + 1 ? <Check /> : index + 1}</span></li>)}</ol>
    <span className="resellerStepPill">Step {step} of 4</span><h1>{steps[step - 1]}</h1><p className="resellerWizardLead">{step === 1 ? "Fill your personal details to get started." : step === 2 ? "Create secure login details for your reseller account." : step === 3 ? "Tell us about your GST registration." : "Tell us about your business to complete registration."}</p>
    {status && <p className="resellerNotice" role="alert">{status}</p>}
    <form className="resellerWizardForm" onSubmit={step === 4 ? submitQuickRegistration : continueStep}>
      {step === 1 && <><label><span><User />Full Name *</span><input required placeholder="Enter your full name" value={quickForm.fullName} onChange={e => update({ fullName: e.target.value })} /></label><label><span><Smartphone />Mobile Number *</span><div className="resellerPhoneInput"><b>+91</b><input required inputMode="numeric" pattern="[0-9]{10}" maxLength="10" placeholder="Enter mobile number" value={quickForm.mobile} onChange={e => update({ mobile: e.target.value.replace(/\D/g, "").slice(0, 10) })} /></div></label><label><span><Mail />Email ID *</span><input required type="email" placeholder="example@gmail.com" value={quickForm.email} onChange={e => update({ email: e.target.value })} /></label></>}
      {step === 2 && <><label><span><LockKeyhole />Create Password *</span><div className="resellerPasswordInput"><input required minLength="8" type={showAccessPassword ? "text" : "password"} value={quickForm.password} onChange={e => update({ password: e.target.value })} /><button type="button" onClick={() => setShowAccessPassword(!showAccessPassword)}>{showAccessPassword ? <EyeOff /> : <Eye />}</button></div><small>Use uppercase, lowercase, number and special character.</small></label><label><span><LockKeyhole />Confirm Password *</span><input required minLength="8" type={showAccessPassword ? "text" : "password"} value={quickForm.confirmPassword} onChange={e => update({ confirmPassword: e.target.value })} /><small className={quickForm.confirmPassword && quickForm.password !== quickForm.confirmPassword ? "errorText" : ""}>{quickForm.confirmPassword ? quickForm.password === quickForm.confirmPassword ? "Passwords match." : "Passwords do not match." : ""}</small></label></>}
      {step === 3 && <><fieldset><legend>GST Registration *</legend><label className="resellerWizardChoice"><input type="radio" checked={quickForm.gstStatus === "gst"} onChange={() => update({ gstStatus: "gst" })} /> GST Registered</label><label className="resellerWizardChoice"><input type="radio" checked={quickForm.gstStatus === "non-gst"} onChange={() => update({ gstStatus: "non-gst", gstin: "", gstState: "", gstCertificate: "", taxVerificationToken: "" })} /> Non-GST</label></fieldset>{quickForm.gstStatus === "gst" && <><label><span><ShieldCheck />GSTIN *</span><div className="resellerVerifyInput"><input required maxLength="15" value={quickForm.gstin} onChange={e => { update({ gstin: e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 15), taxVerificationToken: "", gstState: "", gstCertificate: "" }); setQuickGstVerification({ busy: false, status: "", message: "" }); }} /><button type="button" disabled={quickGstVerification.busy || quickForm.gstin.length !== 15} onClick={verifyQuickGstin}>{quickGstVerification.busy ? "Verifying…" : "Verify"}</button></div></label><label><span><MapPin />Registered State</span><input readOnly value={quickForm.gstState} placeholder="Filled after verification" /></label>{quickGstVerification.message && <p className={`resellerGstMessage ${quickGstVerification.status}`}>{quickGstVerification.message}</p>}<label><span><FileText />GST Certificate *</span><input required={!quickForm.gstCertificate} type="file" accept="image/*,.pdf" disabled={!quickForm.taxVerificationToken || quickCertificate.busy} onChange={async e => { const file = e.target.files?.[0]; if (!file) return; setQuickCertificate({ busy: true, name: file.name, error: "" }); try { const uploaded = await api.uploadSellerRegistrationDocument(file); update({ gstCertificate: uploaded.url }); setQuickCertificate({ busy: false, name: file.name, error: "" }); } catch (error) { setQuickCertificate({ busy: false, name: "", error: error.message }); } }} />{quickForm.gstCertificate && <small className="resellerUploadSuccess"><Check /> Certificate uploaded</small>}</label></>}</>}
      {step === 4 && <><label><span><Store />Shop / Business Name *</span><input required readOnly={quickForm.gstStatus === "gst" && Boolean(quickForm.taxVerificationToken)} placeholder="Enter shop or business name" value={quickForm.businessName} onChange={e => update({ businessName: e.target.value })} /></label><label><span><MapPin />City / Location *</span><input required placeholder="Enter city or area" value={quickForm.city} onChange={e => update({ city: e.target.value })} /></label><label><span><ShoppingBag />Business Type *</span><select required value={quickForm.businessType} onChange={e => update({ businessType: e.target.value })}><option value="">Select business type</option><option>Retail Shop</option><option>Online Seller</option><option>Social Commerce</option><option>Individual Reseller</option><option>Other</option></select></label><label><span><Store />Shop Address *</span><textarea required placeholder="Enter complete address" value={quickForm.address} onChange={e => update({ address: e.target.value })} /></label><label className="resellerWizardTerms"><input required type="checkbox" checked={quickForm.termsAccepted} onChange={e => update({ termsAccepted: e.target.checked })} /> I agree to the Terms &amp; Conditions and Privacy Policy</label></>}
      <button className="resellerWizardPrimary" disabled={accessBusy || quickCertificate.busy || (step === 2 && (!strongPasswordPattern.test(quickForm.password) || quickForm.password !== quickForm.confirmPassword)) || (step === 3 && quickForm.gstStatus === "gst" && (!quickForm.taxVerificationToken || !quickForm.gstCertificate))}>{accessBusy ? "Creating account…" : step === 4 ? "Complete Registration" : "Next"} <ArrowRight /></button>
    </form>
  </section></main>;
}
