import { useState } from "react";
import { api } from "../../services/api.js";
import { money } from "./portalUtils.js";
import BankSummary from "./BankSummary.jsx";
export default function ResellerPayoutPage({ wallet, withdrawals, onChanged, setStatus, onProfile }) {
  const [amount, setAmount] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event) => { event.preventDefault(); setBusy(true); try { await api.requestResellerWithdrawal(Number(amount)); setAmount(""); setStatus("Withdrawal request sent to the administrator."); await onChanged(); } catch (error) { setStatus(error.message); } finally { setBusy(false); } };
  return <section><div className="resellerPageLead"><div><h2>Wallet Withdrawals</h2><p>Request a transfer from your available wallet balance.</p></div></div><div className="resellerPayoutGrid"><form className="resellerPanel resellerWithdrawalForm" onSubmit={submit}><h3>Request withdrawal</h3><strong className="resellerAvailableAmount">{money(wallet.balance)} available</strong><label>Amount<input required type="number" min="1" max={wallet.balance} step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><h4>Transfer will be sent to</h4><BankSummary bank={wallet.bankDetails} />{!wallet.bankDetails?.accountNumber && <button type="button" onClick={onProfile}>Add bank details</button>}<button className="resellerPrimary" disabled={busy || !wallet.bankDetails?.accountNumber || Number(amount) <= 0}>{busy ? "Submitting…" : "Send withdrawal request"}</button></form><section className="resellerPanel resellerOrderTable"><h3>Withdrawal history</h3><table><thead><tr><th>Date</th><th>Amount</th><th>Bank</th><th>Status</th><th>Transaction details</th></tr></thead><tbody>{withdrawals.map(item => <tr key={item._id}><td>{new Date(item.createdAt).toLocaleDateString("en-IN")}</td><td>{money(item.amount)}</td><td>{item.bankSnapshot?.bankName}<br /><small>•••• {item.bankSnapshot?.accountNumber?.slice(-4)}</small></td><td>{item.status}</td><td>{item.paymentReference || item.note || "—"}</td></tr>)}{!withdrawals.length && <tr><td colSpan="5">No withdrawal requests yet.</td></tr>}</tbody></table></section></div></section>;
}
