import { useState } from "react";
import { isReturn, date, money, earning } from "./utils.js";
import Lead from "./Lead.jsx";
import Empty from "./Empty.jsx";
export default function ResellerOrders({ orders, returnsOnly, onSupport }) {
  const [filter,setFilter]=useState("All"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState(null);
  const statuses=returnsOnly ? ["All","Return Requested","Returned","RTO"] : ["All","New","Processing","Shipped","Out for Delivery","Delivered","Cancelled","RTO","Returned","Return Requested"];
  const source=returnsOnly ? orders.filter(isReturn) : orders;
  const matches=source.filter(row=>(filter === "All" || (filter === "New" ? ["Placed","Pending"].includes(row.status) : filter === "Processing" ? ["Confirmed","Packed","Processing"].includes(row.status) : row.status===filter)) && `${row.orderNumber} ${row.items?.map(i=>i.name).join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  return <><Lead title={returnsOnly ? "Returns / RTO" : "My Orders"}>{returnsOnly ? "Track returns and return-to-origin orders. Contact support for assistance." : "Track every order placed through your selling links."}</Lead><div className="rsTabs">{statuses.map(item=><button key={item} className={filter===item?"active":""} aria-pressed={filter===item} onClick={()=>setFilter(item)}>{item}</button>)}</div><input className="rsSearch" aria-label="Search orders" placeholder="Search order number or product…" value={query} onChange={e=>setQuery(e.target.value)}/><section className="resellerPanel resellerOrderTable"><table><thead><tr><th>Order</th><th>Date</th><th>Status</th><th>Order value</th><th>Earning</th><th>Details</th></tr></thead><tbody>{matches.map(order=><tr key={order._id}><td><strong>{order.orderNumber}</strong></td><td>{date(order.createdAt)}</td><td><span className={`resellerStatus ${String(order.status).toLowerCase()}`}>{order.status}</span></td><td>{money(order.grandTotal)}</td><td>{money(earning(order))}</td><td><button className="rsTextButton" onClick={()=>setSelected(order)}>View details</button></td></tr>)}{!matches.length&&<tr><td colSpan="6"><Empty>No orders match this filter.</Empty></td></tr>}</tbody></table></section>{selected&&<section className="resellerPanel rsSection"><header><h3>{selected.orderNumber}</h3><button onClick={()=>setSelected(null)}>Close</button></header><p>Status: <strong>{selected.status}</strong> · Earnings status: {selected.resellerAttribution?.status?.replaceAll("_"," ") || "Pending"}</p>{selected.items?.map((item,i)=><p key={i}>{item.name} × {item.quantity}</p>)}<button className="resellerPrimary" onClick={onSupport}>Get order / return support</button></section>}</>;
}
