import { ChevronRight, Check, ArrowLeft, Link2, Copy, Share2 } from "lucide-react";
import { money } from "./portalUtils.js";
import ResellerProductSearchPage from "./ResellerProductSearchPage.jsx";
import WhatsAppIcon from "../../components/WhatsAppIcon.jsx";
export default function ResellerMarginFlow({ title, addStep, products, selectMarginProduct, selectedProduct, chosenBase, setMargins, margins, chosenMargin, setAddStep, generate, createdLink, sellingUrl, copy, setStatus, setView }) {
  return (<>
          <div className="resellerPageLead"><div><p className="resellerBreadcrumb">Dashboard <ChevronRight /> My Products <ChevronRight /> <b>{title}</b></p><h2>{title}</h2><p>{addStep === 1 ? "Choose an eligible HRSBasket product to add to your catalog." : addStep === 2 ? "Add your margin and create your selling link." : "Your product is ready to share with customers."}</p></div></div>
          <ol className="resellerSteps">{[[1, "Select Product"], [2, "Define Margin"], [3, "Preview & Share"]].map(([step, label]) => <li key={step} className={addStep === step ? "active" : addStep > step ? "complete" : ""}><i>{addStep > step ? <Check /> : step}</i><span>{label}</span></li>)}</ol>
          {addStep === 1 && <ResellerProductSearchPage products={products} onSelect={selectMarginProduct} />}
          {addStep === 2 && selectedProduct && <section className="resellerMarginLayout"><div><article className="resellerSelectedProduct resellerPanel"><h3>Selected Product</h3><div>{selectedProduct.mainImage && <img src={selectedProduct.mainImage} alt="" />}<span><h3>{selectedProduct.name}</h3><p>{selectedProduct.shortDescription}</p><small>In Stock · Available to resell</small></span><aside><small>Base Price</small><strong>{money(chosenBase)}</strong><p>Price before your margin</p></aside></div></article><article className="resellerMarginEditor resellerPanel"><h3>Set Your Margin</h3><label>Your Margin (₹)<div><button onClick={() => setMargins({ ...margins, [selectedProduct._id]: Math.max(0, chosenMargin - 10) })}>−</button><input type="number" min="0" max={selectedProduct.resellerPricing.maximumMargin} value={margins[selectedProduct._id] || 0} onChange={e => setMargins({ ...margins, [selectedProduct._id]: Math.min(Number(selectedProduct.resellerPricing.maximumMargin), Math.max(0, Number(e.target.value))) })} /><button onClick={() => setMargins({ ...margins, [selectedProduct._id]: Math.min(Number(selectedProduct.resellerPricing.maximumMargin), chosenMargin + 10) })}>+</button></div></label><input className="resellerMarginRange" type="range" min="0" max={selectedProduct.resellerPricing.maximumMargin} value={chosenMargin} onChange={e => setMargins({ ...margins, [selectedProduct._id]: Number(e.target.value) })} /><div className="resellerMarginLabels"><span>Min: ₹0</span><span>Recommended: competitive</span><span>Max: {money(selectedProduct.resellerPricing.maximumMargin)}</span></div><div className="resellerMarginSummary"><span>You earn per sale<strong>{money(chosenMargin)}</strong></span><span>Maximum margin<strong>{money(selectedProduct.resellerPricing.maximumMargin)}</strong></span><span>Customer price<strong>{money(chosenBase + chosenMargin)}</strong></span></div><p className="resellerMarginTip">Higher margins increase the customer price. Keep your price competitive to improve sales.</p></article><div className="resellerFlowActions"><button onClick={() => setAddStep(1)}><ArrowLeft /> Back</button><button className="resellerPrimary" disabled={chosenMargin < 0} onClick={() => generate(selectedProduct)}><Link2 /> Create &amp; Preview Link</button></div></div><aside className="resellerPricePreview resellerPanel"><h3>Price Preview</h3><dl><div><dt>Base Price</dt><dd>{money(chosenBase)}</dd></div><div><dt>Your Margin</dt><dd className="positive">+ {money(chosenMargin)}</dd></div><div><dt>Customer Price</dt><dd>{money(chosenBase + chosenMargin)}</dd></div></dl><p><Check /> You will earn <strong>{money(chosenMargin)}</strong> on each sale</p></aside></section>}
          {addStep === 3 && selectedProduct && createdLink && <section className="resellerSharePreview"><article className="resellerShareProduct resellerPanel"><span className="resellerSuccessIcon"><Check /></span><h2>Your selling link is ready!</h2><p>Preview the customer price and share this product with your network.</p>{selectedProduct.mainImage && <img src={selectedProduct.mainImage} alt="" />}<h3>{selectedProduct.name}</h3><dl><div><dt>HRSBasket price</dt><dd>{money(chosenBase)}</dd></div><div><dt>Your margin</dt><dd>{money(createdLink.margin)}</dd></div><div><dt>Customer price</dt><dd>{money(createdLink.customerPrice)}</dd></div></dl><div className="resellerGeneratedLink"><input readOnly value={sellingUrl} /><button onClick={() => copy(sellingUrl)}><Copy /> Copy</button></div><div className="resellerShareButtons"><a href={`https://wa.me/?text=${encodeURIComponent(`${selectedProduct.name} — ${money(createdLink.customerPrice)}\n${sellingUrl}`)}`} target="_blank" rel="noreferrer"><WhatsAppIcon /> WhatsApp</a><button onClick={async () => { try { if (navigator.share) await navigator.share({ title: selectedProduct.name, url: sellingUrl }); else await copy(sellingUrl) } catch (error) { if (error.name !== "AbortError") setStatus(error.message) } }}><Share2 /> Share</button></div><button className="resellerDoneButton" onClick={() => setView("products")}>Done — View My Products</button></article></section>}
        </>);
}
