import express from "express";
import { adminChangePendingPackage, approvePartnerPayment, changePassword, changePendingPackage, createMyRegistrationOrder, createPackage, createRegistrationOrder, dashboard, deletePackage, deletePartner, forgotPartnerPassword, getPublicRegistrationSettings, getReferralPartner, listMyPayouts, listMyWithdrawals, listPackages, listPartners, listPublicPackages, listWithdrawals, loginPartner, lookupIfsc, partnerMe, processWithdrawal, registerPartner, requestBankOtp, requestPartnerRegistrationOtp, requestWithdrawal, requestWithdrawalOtp, resetPartnerForgottenPassword, resetPartnerPassword, revealPartnerPassword, reviewKyc, updateBank, updatePackage, updateProfile, uploadKyc, verifyMyRegistrationPayment, verifyPartnerRegistrationOtp } from "../controllers/partnerController.js";
import { authorize, protect, protectPartner } from "../middleware/authMiddleware.js";

const router = express.Router();
router.get("/packages/public", listPublicPackages);
router.get("/registration-settings", getPublicRegistrationSettings);
router.get("/referrals/:registrationNumber", getReferralPartner);
router.post("/registration/order", createRegistrationOrder);
router.post("/register", registerPartner);
router.post("/registration/otp", requestPartnerRegistrationOtp);
router.post("/registration/verify-otp", verifyPartnerRegistrationOtp);
router.post("/login", loginPartner);
router.post("/forgot-password", forgotPartnerPassword);
router.post("/reset-password", resetPartnerForgottenPassword);
router.get("/me", protectPartner, partnerMe);
router.patch("/package", protectPartner, changePendingPackage);
router.post("/payment/order", protectPartner, createMyRegistrationOrder);
router.post("/payment/verify", protectPartner, verifyMyRegistrationPayment);
router.get("/dashboard", protectPartner, dashboard);
router.patch("/profile", protectPartner, updateProfile);
router.put("/password", protectPartner, changePassword);
router.get("/bank-details/ifsc/:ifsc", protectPartner, lookupIfsc);
router.post("/bank-details/otp", protectPartner, requestBankOtp);
router.put("/bank-details", protectPartner, updateBank);
router.put("/kyc/:type", protectPartner, uploadKyc);
router.get("/payouts", protectPartner, listMyPayouts);
router.post("/withdrawals/otp", protectPartner, requestWithdrawalOtp);
router.route("/withdrawals").get(protectPartner, listMyWithdrawals).post(protectPartner, requestWithdrawal);
router.use("/admin", protect, authorize("Super Admin"));
router.route("/admin/packages").get(listPackages).post(createPackage);
router.route("/admin/packages/:id").put(updatePackage).delete(deletePackage);
router.get("/admin/partners", listPartners);
router.delete("/admin/partners/:id", deletePartner);
router.patch("/admin/partners/:id/payment", approvePartnerPayment);
router.patch("/admin/partners/:id/package", adminChangePendingPackage);
router.get("/admin/partners/:id/password", revealPartnerPassword);
router.post("/admin/partners/:id/reset-password", resetPartnerPassword);
router.patch("/admin/partners/:id/kyc/:type", reviewKyc);
router.get("/admin/withdrawals", listWithdrawals);
router.patch("/admin/withdrawals/:id", processWithdrawal);
export default router;
