import express from "express";
import { authorize, protect, protectCustomer, protectReseller } from "../middleware/authMiddleware.js";
import { adminDetails, adminList, adminProcessWithdrawal, adminReview, adminWithdrawals, createLink, dashboard, links, loginReseller, lookupIfsc, me, orders, payResellerWithdrawal, products, quickRegister, refreshResellerPayoutStatus, register, requestRegistrationOtp, requestWithdrawal, resetResellerPassword, resolveLink, revealResellerPassword, updateBankDetails, wallet, withdrawals } from "../controllers/resellerController.js";
const router = express.Router();
router.get("/links/:code", resolveLink);
router.post("/register/quick", quickRegister);
router.post("/login", loginReseller);
router.post("/registration/otp", protectCustomer, requestRegistrationOtp);
router.post("/register", protectCustomer, register);
router.get("/me", protectReseller, me);
router.get("/bank-details/ifsc/:ifsc", protectReseller, lookupIfsc);
router.put("/bank-details", protectReseller, updateBankDetails);
router.get("/dashboard", protectReseller, dashboard);
router.get("/wallet", protectReseller, wallet);
router.get("/products", protectReseller, products);
router.route("/my-links").get(protectReseller, links).post(protectReseller, createLink);
router.get("/orders", protectReseller, orders);
router.route("/withdrawals").get(protectReseller, withdrawals).post(protectReseller, requestWithdrawal);
// Keep the more-specific password endpoints before the generic account ID route.
router.get("/admin/accounts/:id/password", protect, authorize("Super Admin"), revealResellerPassword);
router.post("/admin/accounts/:id/reset-password", protect, authorize("Super Admin"), resetResellerPassword);
router.get("/admin/accounts", protect, authorize("Super Admin", "Team Leader", "Staff"), adminList);
router.get("/admin/accounts/:id", protect, authorize("Super Admin", "Team Leader", "Staff"), adminDetails);
router.patch("/admin/accounts/:id", protect, authorize("Super Admin", "Team Leader", "Staff"), adminReview);
router.get("/admin/withdrawals", protect, authorize("Super Admin", "Finance Manager"), adminWithdrawals);
router.patch("/admin/withdrawals/:id", protect, authorize("Super Admin", "Finance Manager"), adminProcessWithdrawal);
router.post("/admin/withdrawals/:id/payout", protect, authorize("Super Admin", "Finance Manager"), payResellerWithdrawal);
router.post("/admin/withdrawals/:id/payout/status", protect, authorize("Super Admin", "Finance Manager"), refreshResellerPayoutStatus);
export default router;
