import express from "express";
import { authorize, protect, protectCustomer, protectReseller } from "../middleware/authMiddleware.js";
import { adminDetails, adminList, adminProcessWithdrawal, adminReview, adminWithdrawals, createLink, dashboard, links, me, orders, products, quickRegister, register, requestRegistrationOtp, requestWithdrawal, resolveLink, withdrawals } from "../controllers/resellerController.js";
const router = express.Router();
router.get("/links/:code", resolveLink);
router.post("/register/quick", quickRegister);
router.post("/registration/otp", protectCustomer, requestRegistrationOtp);
router.post("/register", protectCustomer, register);
router.get("/me", protectReseller, me);
router.get("/dashboard", protectReseller, dashboard);
router.get("/products", protectReseller, products);
router.route("/my-links").get(protectReseller, links).post(protectReseller, createLink);
router.get("/orders", protectReseller, orders);
router.route("/withdrawals").get(protectReseller, withdrawals).post(protectReseller, requestWithdrawal);
router.get("/admin/accounts", protect, authorize("Super Admin", "Team Leader", "Staff"), adminList);
router.get("/admin/accounts/:id", protect, authorize("Super Admin", "Team Leader", "Staff"), adminDetails);
router.patch("/admin/accounts/:id", protect, authorize("Super Admin", "Team Leader", "Staff"), adminReview);
router.get("/admin/withdrawals", protect, authorize("Super Admin", "Finance Manager"), adminWithdrawals);
router.patch("/admin/withdrawals/:id", protect, authorize("Super Admin", "Finance Manager"), adminProcessWithdrawal);
export default router;
