import express from "express";
import { approveSeller, approveSellerProduct, changeSellerPassword, createSellerProduct, forgotSellerPassword, generateSellerInvoice, listAdminSellerProducts, listAdminSellerWithdrawals, listMyProducts, listPendingSellerProducts, listSellerOrders, listSellerWithdrawals, listSellers, loginSeller, lookupSellerIfsc, lookupSellerReferral, paySellerWithdrawal, processSellerWithdrawal, requestSellerRegistrationOtp, requestSellerWithdrawal, verifySellerRegistrationOtp, rejectSeller, rejectSellerProduct, resetSellerForgottenPassword, resetSellerPassword, revealSellerPassword, reviewSellerKyc, settleSellerOrderItem, syncSellerShipRocket, toggleSellerProduct, updateSellerBank, updateSellerCommission, updateSellerCompliance, updateSellerItemReturn, updateSellerOrderItem, updateSellerProduct, updateSellerProfile, uploadSellerKyc, sellerCatalogOptions, sellerDashboard, sellerMe, sellerWallet } from "../controllers/sellerController.js";
import { authorize, protect, protectSeller } from "../middleware/authMiddleware.js";

const router = express.Router();
router.post("/registration/otp", requestSellerRegistrationOtp);
router.post("/registration/verify-otp", verifySellerRegistrationOtp);
router.get("/referrals/:sellerNumber", lookupSellerReferral);
router.post("/login", loginSeller);
router.post("/forgot-password", forgotSellerPassword);
router.post("/reset-password", resetSellerForgottenPassword);
router.get("/me", protectSeller, sellerMe);
router.get("/dashboard", protectSeller, sellerDashboard);
router.get("/catalog-options", protectSeller, sellerCatalogOptions);
router.patch("/profile", protectSeller, updateSellerProfile);
router.get("/bank-details/ifsc/:ifsc", protectSeller, lookupSellerIfsc);
router.put("/bank-details", protectSeller, updateSellerBank);
router.put("/password", protectSeller, changeSellerPassword);
router.put("/kyc/:type", protectSeller, uploadSellerKyc);
router.route("/products").get(protectSeller, listMyProducts).post(protectSeller, createSellerProduct);
router.put("/products/:id", protectSeller, updateSellerProduct);
router.patch("/products/:id/enabled", protectSeller, toggleSellerProduct);
router.get("/orders", protectSeller, listSellerOrders);
router.get("/wallet", protectSeller, sellerWallet);
router.route("/withdrawals").get(protectSeller, listSellerWithdrawals).post(protectSeller, requestSellerWithdrawal);
router.post("/orders/:orderId/invoice", protectSeller, generateSellerInvoice);
router.post("/orders/:orderId/shiprocket", protectSeller, syncSellerShipRocket);
router.patch("/orders/:orderId/items/:productId", protectSeller, updateSellerOrderItem);
router.post("/orders/:orderId/items/:productId/settle", protectSeller, settleSellerOrderItem);
router.patch("/orders/:orderId/items/:productId/return", protectSeller, updateSellerItemReturn);
router.use("/admin", protect, authorize("Super Admin"));
router.get("/admin", listSellers);
router.get("/admin/products/pending", listPendingSellerProducts);
router.get("/admin/withdrawals", listAdminSellerWithdrawals);
router.patch("/admin/withdrawals/:id", processSellerWithdrawal);
router.post("/admin/withdrawals/:id/payout", paySellerWithdrawal);
router.get("/admin/:id/password", revealSellerPassword);
router.post("/admin/:id/reset-password", resetSellerPassword);
router.get("/admin/:id/products", listAdminSellerProducts);
router.patch("/admin/:id/commission", updateSellerCommission);
router.patch("/admin/:id/compliance", updateSellerCompliance);
router.patch("/admin/:id/approve", approveSeller);
router.patch("/admin/:id/reject", rejectSeller);
router.patch("/admin/:id/products/:productId/approve", approveSellerProduct);
router.patch("/admin/:id/products/:productId/reject", rejectSellerProduct);
router.patch("/admin/:id/kyc/:type", reviewSellerKyc);
export default router;
