import express from "express";
import { approveSeller, approveSellerProduct, changeSellerPassword, createSellerProduct, forgotSellerPassword, generateSellerInvoice, getAdminSellerReferrals, listAdminSellerProducts, listAdminSellerTransactions, listAdminSellerWithdrawals, listMyProducts, listPendingSellerProducts, listSellerOrders, listSellerReferrals, listSellerTransactions, listSellerWithdrawals, listSellers, loginSeller, lookupSellerIfsc, lookupSellerReferral, paySellerWithdrawal, processSellerWithdrawal, requestSellerBankOtp, requestSellerPayoutOtp, requestSellerRegistrationOtp, requestSellerWithdrawal, requestSellerWithdrawalOtp, verifySellerRegistrationOtp, rejectSeller, rejectSellerProduct, resetSellerForgottenPassword, resetSellerPassword, revealSellerPassword, reviewAdminSellerSettlement, reviewSellerKyc, saveSellerManualCourier, settleSellerOrderItem, syncSellerShipRocket, toggleSellerProduct, updateSellerBank, updateSellerByAdmin, updateSellerCommission, updateSellerCompliance, updateSellerItemReturn, updateSellerOrderItem, updateSellerProduct, updateSellerProfile, uploadSellerKyc, sellerCatalogOptions, sellerDashboard, sellerMe, sellerWallet } from "../controllers/sellerController.js";
import { verifySellerTaxIdentifier } from "../controllers/sellerController.js";
import { authorize, protect, protectSeller } from "../middleware/authMiddleware.js";

const router = express.Router();
router.post("/registration/otp", requestSellerRegistrationOtp);
router.post("/registration/verify-otp", verifySellerRegistrationOtp);
router.post("/registration/verify-tax", verifySellerTaxIdentifier);
router.get("/referrals/:sellerNumber", lookupSellerReferral);
router.post("/login", loginSeller);
router.post("/forgot-password", forgotSellerPassword);
router.post("/reset-password", resetSellerForgottenPassword);
router.get("/me", protectSeller, sellerMe);
router.get("/dashboard", protectSeller, sellerDashboard);
router.get("/my-referrals", protectSeller, listSellerReferrals);
router.get("/catalog-options", protectSeller, sellerCatalogOptions);
router.patch("/profile", protectSeller, updateSellerProfile);
router.get("/bank-details/ifsc/:ifsc", protectSeller, lookupSellerIfsc);
router.post("/bank-details/otp", protectSeller, requestSellerBankOtp);
router.put("/bank-details", protectSeller, updateSellerBank);
router.put("/password", protectSeller, changeSellerPassword);
router.put("/kyc/:type", protectSeller, uploadSellerKyc);
router.route("/products").get(protectSeller, listMyProducts).post(protectSeller, createSellerProduct);
router.put("/products/:id", protectSeller, updateSellerProduct);
router.patch("/products/:id/enabled", protectSeller, toggleSellerProduct);
router.get("/orders", protectSeller, listSellerOrders);
router.get("/wallet", protectSeller, sellerWallet);
router.get("/transactions", protectSeller, listSellerTransactions);
router.route("/withdrawals").get(protectSeller, listSellerWithdrawals).post(protectSeller, requestSellerWithdrawal);
router.post("/withdrawals/otp", protectSeller, requestSellerWithdrawalOtp);
router.post("/orders/:orderId/invoice", protectSeller, generateSellerInvoice);
router.post("/orders/:orderId/shiprocket", protectSeller, syncSellerShipRocket);
router.post("/orders/:orderId/manual-courier", protectSeller, saveSellerManualCourier);
router.patch("/orders/:orderId/items/:productId", protectSeller, updateSellerOrderItem);
router.post("/orders/:orderId/items/:productId/settle", protectSeller, settleSellerOrderItem);
router.get("/admin/withdrawals", protect, listAdminSellerWithdrawals);
router.patch("/admin/withdrawals/:id", protect, processSellerWithdrawal);
router.post("/admin/withdrawals/:id/payout/otp", protect, requestSellerPayoutOtp);
router.post("/admin/withdrawals/:id/payout", protect, paySellerWithdrawal);
router.use("/admin", protect, authorize("Super Admin"));
router.get("/admin", listSellers);
router.route("/admin/:id").put(updateSellerByAdmin).patch(updateSellerByAdmin);
router.get("/admin/products/pending", listPendingSellerProducts);
router.get("/admin/:id/transactions", listAdminSellerTransactions);
router.get("/admin/:id/referrals", getAdminSellerReferrals);
router.post("/admin/orders/:orderId/items/:productId/settlement", reviewAdminSellerSettlement);
router.get("/admin/:id/password", revealSellerPassword);
router.post("/admin/:id/reset-password", resetSellerPassword);
router.get("/admin/:id/products", listAdminSellerProducts);
router.patch("/admin/:id/commission", updateSellerCommission);
router.patch("/admin/:id/compliance", updateSellerCompliance);
router.patch("/admin/:id/approve", approveSeller);
router.patch("/admin/:id/reject", rejectSeller);
router.patch("/admin/:id/products/:productId/approve", approveSellerProduct);
router.patch("/admin/:id/products/:productId/reject", rejectSellerProduct);
router.patch("/admin/:id/kyc/:type", reviewSellerKyc);
export default router;
