import { router } from 'expo-router';
import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Screen } from '@/components/Screen';
import { Button, Field, Chip } from '@/components/Ui';
import { PaymentSheet, PaymentSession } from '@/components/PaymentSheet';
import { useAuth } from '@/context/AuthContext';
import { useShop } from '@/context/ShopContext';
import { api } from '@/lib/api';
import { money, orderItems } from '@/lib/commerce';
import { colors } from '@/theme';
import type { Address } from '@/types';
export default function Checkout(){
 const {customer,ready}=useAuth();const {cart,subtotal,clearCart}=useShop();const [f,setF]=useState({name:'',email:'',phone:'',billingAddress:'',billingCity:'',billingState:'',billingPostalCode:'',shippingAddress:'',city:'',state:'',postalCode:''});
 const [same,setSame]=useState(true);const [methods,setMethods]=useState<any[]>([]);const [method,setMethod]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [otp,setOtp]=useState('');const [challenge,setChallenge]=useState('');const [verified,setVerified]=useState(false);const [quote,setQuote]=useState<any>();const [quoting,setQuoting]=useState(false);const [session,setSession]=useState<PaymentSession|null>(null);const [pending,setPending]=useState<any>();const [completed,setCompleted]=useState<any[]>([]);const submitting=useRef(false);
 const owner=customer?.id||customer?._id;const pendingKey=`customer_pending_payment_${owner}`;
 useEffect(()=>{if(ready&&!customer)router.replace({pathname:'/login',params:{redirect:'/checkout'}})},[ready,customer]);
 const useAddress=(a:Address)=>setF(x=>({...x,billingAddress:a.line1,billingCity:a.city,billingState:a.state,billingPostalCode:a.postalCode}));
 useEffect(()=>{if(!customer)return;setF(x=>({...x,name:customer.name,email:customer.email,phone:customer.phone||''}));const a=customer.addresses?.find(a=>a.isDefault)||customer.addresses?.[0];if(a)useAddress(a);api.paymentMethods().then(setMethods).catch(e=>setError(e.message));AsyncStorage.getItem(pendingKey).then(value=>{if(value)setPending(JSON.parse(value))}).catch(()=>{})},[owner]);
 const eligible=methods.filter(m=>['cod','razorpay','payu'].includes(m.type)&&(Platform.OS!=='web'||m.type==='cod')&&cart.every(i=>!i.product.seller||(m.type==='cod'?i.product.codAvailable===true:i.product.prepaidAvailable!==false)));
 const selected=eligible.find(m=>m.code===method)||eligible[0];const postal=same?f.billingPostalCode:f.postalCode;
 useEffect(()=>{let cancelled=false;setQuote(undefined);if(!/^\d{6}$/.test(postal)||!cart.length||!selected){setQuoting(false);return;}setQuoting(true);const t=setTimeout(()=>api.checkoutQuote({pincode:postal,state:same?f.billingState:f.state,items:orderItems(cart),paymentMethodCode:selected.code}).then(r=>{if(!cancelled){setQuote(r);setError('')}}).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{if(!cancelled)setQuoting(false)}),450);return()=>{cancelled=true;clearTimeout(t)}},[postal,cart,selected?.code,same,f.billingState,f.state]);
 const payload=()=>({items:orderItems(cart),checkout:{...f,...(same?{shippingAddress:f.billingAddress,city:f.billingCity,state:f.billingState,postalCode:f.billingPostalCode}:{})},paymentMethodCode:selected?.code,otpChallengeId:challenge});
 const finish=async(value:any)=>{const result=await api.createOrder(value);await AsyncStorage.removeItem(pendingKey);setPending(undefined);setCompleted(result.orders||[result.order]);clearCart();setSession(null)};
 const savePayment=async(value:any)=>{await AsyncStorage.setItem(pendingKey,JSON.stringify(value));setPending(value)};
 const validate=()=>{if(!cart.length)throw new Error('Your cart is empty');if(!selected)throw new Error('No payment method is available for this cart');if(Object.values(payload().checkout).some(v=>!String(v).trim()))throw new Error('Complete contact and address fields');if(!/^\d{6}$/.test(f.billingPostalCode)||!/^\d{6}$/.test(postal))throw new Error('Enter valid 6-digit pincodes');if(!quote||quoting)throw new Error('Wait for a valid shipping quote');if(selected.type==='cod'&&quote.codAvailable===false)throw new Error('Cash on delivery is unavailable for this address')};
 const sendOtp=async()=>{setBusy(true);setError('');try{validate();const r=await api.orderOtp({});setChallenge(r.challengeId);setVerified(false);setOtp('')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const place=async()=>{if(submitting.current)return;submitting.current=true;setBusy(true);setError('');try{validate();const value=payload();if(selected.type==='cod'){if(!challenge||!/^[0-9]{6}$/.test(otp))throw new Error('Request and enter the email OTP');if(!verified){await api.orderOtp({challengeId:challenge,otp});setVerified(true)}await finish(value)}else{const data=selected.type==='razorpay'?await api.razorpay(value):await api.payu({...value,firstname:f.name,phone:f.phone});await savePayment({payload:value,type:selected.type,data});setSession({type:selected.type,data,name:f.name,email:f.email,phone:f.phone})}}catch(e:any){setError(e.message)}finally{setBusy(false);submitting.current=false}};
 const paymentComplete=async(r:any)=>{setSession(null);if(!r.ok){setError(r.error||'Payment was unsuccessful');return;}if(submitting.current)return;submitting.current=true;setBusy(true);try{const value={...pending.payload,...(pending.type==='payu'?{payuTxnId:r.txnid}:{razorpayOrderId:r.razorpayOrderId,razorpayPaymentId:r.razorpayPaymentId,razorpaySignature:r.razorpaySignature})};await savePayment({...pending,verifiedPayload:value});await finish(value)}catch(e:any){setError(`Payment received; order confirmation needs a retry. ${e.message}`)}finally{submitting.current=false;setBusy(false)}};
 const recover=async()=>{setBusy(true);setError('');try{if(pending.verifiedPayload)await finish(pending.verifiedPayload);else if(pending.type==='payu'){const r=await api.payuStatus(pending.data.fields.txnid);if(r.status!=='success')throw new Error('Payment is not confirmed yet. Try again or contact support.');await finish({...pending.payload,payuTxnId:pending.data.fields.txnid})}else{setSession({type:pending.type,data:pending.data,name:f.name,email:f.email,phone:f.phone})}}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 if(!ready)return <Screen title="Checkout" back><ActivityIndicator/></Screen>;if(!customer)return null;
 if(completed.length)return <Screen title="Order confirmed" back><ScrollView contentContainerStyle={s.content}><Text style={s.heading}>Thank you, {customer.name.split(' ')[0]}!</Text><Text>Your order{completed.length>1?'s have':' has'} been placed.</Text>{completed.map(o=><View key={o._id} style={s.card}><Text style={s.heading}>{o.orderNumber}</Text><Text>{money(o.grandTotal)}</Text></View>)}<Button title="View my orders" onPress={()=>router.replace('/orders')}/><Button title="Continue shopping" variant="outline" onPress={()=>router.replace('/(tabs)/shop')}/></ScrollView></Screen>;
 const estimated=Number(quote?.total||0);
 return <Screen title="Checkout" back><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}>
 {pending&&<View style={s.card}><Text style={s.heading}>Pending payment</Text><Text>Resume payment or retry order confirmation before paying again.</Text><Button title="Resume / confirm payment" loading={busy} onPress={recover}/></View>}
 <Text style={s.heading}>Contact</Text><Field label="Full name" value={f.name} onChangeText={name=>setF(x=>({...x,name}))}/><Field label="Account email" value={f.email} editable={false}/><Field label="Phone" value={f.phone} onChangeText={phone=>setF(x=>({...x,phone}))} keyboardType="phone-pad"/>
 <Text style={s.heading}>Billing address</Text><ScrollView horizontal contentContainerStyle={{gap:8}}>{customer.addresses?.map((a,i)=><Chip key={a._id||i} label={a.label} onPress={()=>useAddress(a)}/>)}</ScrollView>
 {(['billingAddress','billingCity','billingState','billingPostalCode'] as const).map(k=><Field key={k} label={{billingAddress:'Street address',billingCity:'City',billingState:'State',billingPostalCode:'Pincode'}[k]} value={f[k]} onChangeText={v=>setF(x=>({...x,[k]:v}))} keyboardType={k==='billingPostalCode'?'number-pad':'default'}/>)}
 <Pressable onPress={()=>setSame(v=>!v)}><Text style={s.link}>{same?'☑':'☐'} Ship to billing address</Text></Pressable>
 {!same&&(['shippingAddress','city','state','postalCode'] as const).map(k=><Field key={k} label={{shippingAddress:'Shipping street address',city:'City',state:'State',postalCode:'Pincode'}[k]} value={f[k]} onChangeText={v=>setF(x=>({...x,[k]:v}))} keyboardType={k==='postalCode'?'number-pad':'default'}/>)}
 <Text style={s.heading}>Payment</Text>{eligible.map(m=><Pressable key={m.code} onPress={()=>setMethod(m.code)} style={[s.card,m.code===selected?.code&&{borderColor:colors.primary}]}><Text style={s.link}>{m.code===selected?.code?'●':'○'} {m.name}</Text>{m.instructions&&<Text>{m.instructions}</Text>}</Pressable>)}{!eligible.length&&<Text>No payment methods are available for this cart.</Text>}
 {selected?.type==='cod'&&<View style={s.card}><Text>Verify your account email to confirm cash on delivery.</Text><Button title={challenge?'Resend email OTP':'Send email OTP'} variant="outline" loading={busy} onPress={sendOtp}/>{challenge&&<Field label="6-digit OTP" value={otp} onChangeText={v=>setOtp(v.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" textContentType="oneTimeCode" autoComplete="one-time-code"/>}</View>}
 {quoting&&<ActivityIndicator/>}{quote&&<View style={s.card}><Text>Products: {money(quote.subtotal)}</Text><Text>Shipping: {money(quote.shippingAmount)}</Text><Text>COD charge: {money(quote.codCharge)}</Text><Text>Discount: −{money(quote.discountTotal)}</Text><Text style={s.heading}>Total: {money(estimated)}</Text></View>}{error&&<Text style={s.error}>{error}</Text>}<Button title={selected?.type==='cod'?'Confirm order':'Continue to payment'} loading={busy} disabled={!quote||quoting||!!pending} onPress={place}/>
 </ScrollView></KeyboardAvoidingView><PaymentSheet session={session} onComplete={paymentComplete} onCancel={()=>{setSession(null);setError('Payment closed. Resume the pending payment to continue.')}}/></Screen>;
}
const s=StyleSheet.create({content:{padding:20,gap:14,paddingBottom:40,width:'100%',maxWidth:720,alignSelf:'center'},heading:{fontSize:20,fontWeight:'900',color:colors.ink},card:{backgroundColor:'white',padding:16,borderRadius:15,gap:12,borderWidth:1,borderColor:colors.line},link:{color:colors.primary,fontWeight:'800'},error:{backgroundColor:'#fff0f0',color:colors.danger,padding:14,borderRadius:12}});
