import { router } from 'expo-router';
import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,FlatList,Pressable,StyleSheet,Text,View } from 'react-native';
import { Screen } from '@/components/Screen';
import { Button,EmptyState } from '@/components/Ui';
import { useAuth } from '@/context/AuthContext';
import { api } from '@/lib/api';
import { money } from '@/lib/commerce';
import { colors } from '@/theme';
import type { Order } from '@/types';
export default function Orders(){const {customer,ready}=useAuth();const [orders,setOrders]=useState<Order[]>([]);const [page,setPage]=useState(1);const [pages,setPages]=useState(1);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const load=useCallback(async(p=1)=>{setLoading(true);setError('');try{const r=await api.orders(p);setOrders(r.items||[]);setPage(p);setPages(r.pagination?.pages||1)}catch(e:any){setError(e.message)}finally{setLoading(false)}},[]);useEffect(()=>{if(!ready)return;if(!customer)router.replace('/login');else void load()},[ready,customer?.id]);return <Screen title="My orders" back>{error&&<View style={{padding:16,gap:10}}><Text style={{color:colors.danger}}>{error}</Text><Button title="Retry" onPress={()=>load(page)}/></View>}<FlatList data={orders} keyExtractor={o=>o._id} refreshing={loading} onRefresh={()=>load(page)} contentContainerStyle={s.list} ListEmptyComponent={loading?<ActivityIndicator/>:<EmptyState title="No orders yet" message="Your purchases will appear here."/>} renderItem={({item})=><Pressable onPress={()=>router.push({pathname:'/order/[id]',params:{id:item._id,number:item.orderNumber}})} style={s.card}><View style={s.row}><Text style={s.number}>{item.orderNumber}</Text><Text style={s.status}>{item.items?.[0]?.sellerStatus||item.status}</Text></View><Text style={s.muted}>{new Date(item.createdAt).toLocaleDateString('en-IN')} · {item.items.length} items</Text><View style={s.row}><Text style={s.number}>{money(item.grandTotal)}</Text><Text style={s.status}>Details & tracking ›</Text></View></Pressable>} ListFooterComponent={pages>1?<View style={s.row}><Button title="Previous" disabled={page<=1||loading} onPress={()=>load(page-1)}/><Text>{page} / {pages}</Text><Button title="Next" disabled={page>=pages||loading} onPress={()=>load(page+1)}/></View>:null}/></Screen>}
const s=StyleSheet.create({list:{padding:16,gap:14},card:{backgroundColor:'white',padding:18,gap:12,borderRadius:16,borderWidth:1,borderColor:colors.line},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},number:{fontSize:16,fontWeight:'900'},status:{color:colors.primary,fontWeight:'800'},muted:{color:colors.muted}});
