import { router } from 'expo-router';
import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { Screen } from '@/components/Screen';
import { Button,Chip,Field } from '@/components/Ui';
import { useAuth } from '@/context/AuthContext';
import { api } from '@/lib/api';
import { colors } from '@/theme';
import type { Address } from '@/types';
const blank:Address={label:'Home',line1:'',city:'',state:'',postalCode:'',country:'India',isDefault:false};
export default function Profile(){
 const {customer,ready,refresh}=useAuth();const [f,setF]=useState({name:customer?.name||'',phone:customer?.phone||'',gender:customer?.gender||'prefer_not_to_say'});const [addresses,setAddresses]=useState<Address[]>([]);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const [password,setPassword]=useState({currentPassword:'',newPassword:''});
 useEffect(()=>{if(!ready)return;if(!customer){router.replace('/login');return;}api.account().then(r=>{setF({name:r.customer.name,phone:r.customer.phone||'',gender:r.customer.gender||'prefer_not_to_say'});setAddresses(r.customer.addresses||[])}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false))},[ready,customer?.id]);
 const save=async(action:()=>Promise<any>)=>{setBusy(true);setMessage('');try{const r=await action();await refresh();setMessage(r.message||'Saved successfully.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const update=(index:number,key:keyof Address,value:string|boolean)=>setAddresses(items=>items.map((a,i)=>i===index?{...a,[key]:value}:key==='isDefault'&&value?{...a,isDefault:false}:a));
 return <Screen title="Profile & addresses" back><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}>{loading?<ActivityIndicator/>:<><Text style={s.heading}>Personal information</Text><Field label="Name" value={f.name} onChangeText={name=>setF(x=>({...x,name}))}/><Field label="Email" value={customer?.email} editable={false}/><Field label="Phone" value={f.phone} onChangeText={phone=>setF(x=>({...x,phone}))} keyboardType="phone-pad"/><ScrollView horizontal contentContainerStyle={{gap:8}}>{['female','male','other','prefer_not_to_say'].map(v=><Chip key={v} label={v.replaceAll('_',' ')} selected={f.gender===v} onPress={()=>setF(x=>({...x,gender:v}))}/>)}</ScrollView><Button title="Save profile" loading={busy} onPress={()=>save(()=>api.updateProfile(f))}/>
 <Text style={s.heading}>Delivery addresses</Text>{addresses.map((a,i)=><View key={i} style={s.card}>{(['label','line1','city','state','postalCode','country'] as const).map(key=><Field key={key} label={{label:'Label',line1:'Street address',city:'City',state:'State',postalCode:'Pincode',country:'Country'}[key]} value={a[key]} onChangeText={v=>update(i,key,v)} keyboardType={key==='postalCode'?'number-pad':'default'}/>)}<Pressable onPress={()=>update(i,'isDefault',!a.isDefault)}><Text style={s.link}>{a.isDefault?'☑':'☐'} Default address</Text></Pressable><Button title="Remove address" variant="outline" onPress={()=>setAddresses(x=>x.filter((_,j)=>j!==i))}/></View>)}<Button title="Add address" variant="outline" onPress={()=>setAddresses(x=>[...x,{...blank,isDefault:!x.length}])}/><Button title="Save addresses" loading={busy} onPress={()=>save(()=>api.addresses(addresses))}/>
 <Text style={s.heading}>Change password</Text><Field label="Current password" value={password.currentPassword} onChangeText={currentPassword=>setPassword(x=>({...x,currentPassword}))} secureTextEntry/><Field label="New password (8+ characters)" value={password.newPassword} onChangeText={newPassword=>setPassword(x=>({...x,newPassword}))} secureTextEntry/><Button title="Change password" loading={busy} onPress={()=>save(async()=>{const r=await api.changePassword(password);setPassword({currentPassword:'',newPassword:''});return r})}/></>}{message&&<Text style={s.note}>{message}</Text>}</ScrollView></Screen>;
}
const s=StyleSheet.create({content:{padding:20,gap:16,paddingBottom:40,maxWidth:720,width:'100%',alignSelf:'center'},heading:{fontSize:21,fontWeight:'900',color:colors.ink},card:{padding:16,backgroundColor:'white',borderRadius:16,gap:12,borderWidth:1,borderColor:colors.line},link:{color:colors.primary,fontWeight:'800'},note:{padding:14,backgroundColor:colors.primarySoft,borderRadius:12}});
