import { useEffect, useState } from "react";
import { ImagePlus, Plus, Trash2 } from "lucide-react";

const fileData = (file) => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); });
const blankBanner = { title: "", imageUrl: "", product: "", isActive: true, sortOrder: 1 };

export default function BannerAdminPage({ settings, products, onSave }) {
  const [columns, setColumns] = useState(settings.productBannerColumns || 2);
  const [banners, setBanners] = useState(settings.productBanners || []);
  const [form, setForm] = useState(blankBanner);
  useEffect(() => { setColumns(settings.productBannerColumns || 2); setBanners(settings.productBanners || []); }, [settings]);
  const saveAll = async (nextBanners = banners, nextColumns = columns) => { const { _id: _settingsId, createdAt: _createdAt, updatedAt: _updatedAt, __v: _version, ...editableSettings } = settings; const payload = { ...editableSettings, productBannerColumns: Number(nextColumns), productBanners: nextBanners.map((item, index) => ({ ...item, product: item.product?._id || item.product, sortOrder: item.sortOrder || index + 1 })) }; await onSave(payload); };
  const add = async (event) => { event.preventDefault(); const next = [...banners, { ...form, sortOrder: banners.length + 1 }]; setBanners(next); setForm(blankBanner); await saveAll(next, columns); };
  return <section className="contentStack"><form className="panel formGrid twoColumn" onSubmit={add}><div className="panelHeader full"><h2>Add product banner</h2><ImagePlus size={18} /></div><label>Title<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Linked product<select required value={form.product} onChange={(event) => setForm({ ...form, product: event.target.value })}><option value="">Select product</option>{products.filter((product) => product.status === "active" && (!product.seller || (product.sellerEnabled !== false && ["approved", "pending_update", "rejected_update"].includes(product.approvalStatus)))).map((product) => <option key={product._id} value={product._id}>{product.name} · {product.sku}</option>)}</select></label><label className="full">Banner image<input type="file" accept="image/*" required={!form.imageUrl} onChange={async (event) => setForm({ ...form, imageUrl: await fileData(event.target.files[0]) })} /></label><label>Layout<select value={columns} onChange={(event) => setColumns(Number(event.target.value))}><option value="1">One column</option><option value="2">Two columns</option></select></label><label className="toggleRow"><input type="checkbox" checked={form.isActive} onChange={(event) => setForm({ ...form, isActive: event.target.checked })} /><span>Active</span></label><button className="primaryButton"><Plus size={17} />Add banner</button></form><div className="panel tableWrap"><div className="panelHeader"><h2>Banners below hero</h2><button className="primaryButton" type="button" onClick={() => saveAll(banners, columns)}>Save layout</button></div><table><thead><tr><th>Preview</th><th>Title</th><th>Product</th><th>Active</th><th>Action</th></tr></thead><tbody>{banners.map((banner, index) => <tr key={banner._id || index}><td><img className="tableThumb bannerThumb" src={banner.imageUrl} alt="" /></td><td>{banner.title || "—"}</td><td>{banner.product?.name || products.find((product) => product._id === banner.product)?.name || "—"}</td><td><input type="checkbox" checked={banner.isActive !== false} onChange={(event) => setBanners(banners.map((item, itemIndex) => itemIndex === index ? { ...item, isActive: event.target.checked } : item))} /></td><td><button type="button" title="Delete" onClick={async () => { const next = banners.filter((_item, itemIndex) => itemIndex !== index); setBanners(next); await saveAll(next, columns); }}><Trash2 size={16} /></button></td></tr>)}</tbody></table></div></section>;
}
