import { useEffect, useRef, useState } from "react";
import { GripVertical, Plus, Save, Trash2 } from "lucide-react";

const blankPage = { title: "", slug: "", content: "" };
const slugify = (value) => String(value).toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export function PagesAdminPage({ settings, onAdd, onEdit, onDelete }) {
  const pages = [...(settings.pages || [])].sort((a, b) => String(a.title).localeCompare(String(b.title)));
  return <section className="contentStack"><div className="panelHeader"><div><h2>Pages</h2><p className="mutedText">Create and manage storefront content pages.</p></div><button className="primaryButton" type="button" onClick={onAdd}><Plus size={17} />Add page</button></div><div className="panel tableWrap"><table><thead><tr><th>Title</th><th>URL</th><th>Content</th><th>Action</th></tr></thead><tbody>{pages.map((page) => <tr key={page._id || page.slug}><td><strong>{page.title}</strong></td><td>/page/{page.slug}</td><td>{page.content ? stripHtml(page.content).slice(0, 80) : "—"}</td><td><button className="inlineButton" type="button" onClick={() => onEdit(page)}>Edit</button><button className="inlineButton" type="button" onClick={() => onDelete(page)}>Delete</button></td></tr>)}{!pages.length && <tr><td colSpan="4">No pages have been created.</td></tr>}</tbody></table></div></section>;
}

export function PageEditorPage({ initialPage, onBack, onSave }) {
  const [form, setForm] = useState(initialPage || blankPage);
  return <form className="contentStack pageEditorPage" onSubmit={(event) => { event.preventDefault(); onSave({ ...form, title: form.title.trim(), slug: slugify(form.slug || form.title) }); }}><div className="panelHeader"><div><h2>{initialPage ? "Edit page" : "Add page"}</h2><p className="mutedText">Build the storefront page content with the rich-text editor.</p></div><button className="inlineButton" type="button" onClick={onBack}>Back to pages</button></div><section className="panel formPanel"><label><span>Page title</span><input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value, slug: form.slug || slugify(event.target.value) })} /></label><label><span>URL slug</span><input required value={form.slug} onChange={(event) => setForm({ ...form, slug: slugify(event.target.value) })} /></label><label><span>Content</span><RichTextEditor value={form.content} onChange={(content) => setForm({ ...form, content })} /></label><button className="primaryButton"><Save size={17} />Save page</button></section></form>;
}

export function FooterAdminPage({ settings, onSave }) {
  const [columns, setColumns] = useState(settings.footerColumns || []); const pages = settings.pages || [];
  const save = async (next = columns) => { const ordered = next.map((column, sortOrder) => ({ ...column, sortOrder })); setColumns(ordered); await onSave({ ...settings, footerColumns: ordered }); };
  const move = (from, to) => { const next = [...columns]; const [column] = next.splice(from, 1); next.splice(to, 0, column); save(next); };
  return <section className="contentStack"><div className="panelHeader"><div><h2>Footer</h2><p className="mutedText">Add 2–4 columns. Drag a column to change its sequence.</p></div><button className="primaryButton" type="button" disabled={columns.length >= 4} onClick={() => save([...columns, { title: "", type: "links", text: "", links: [], pageIds: [] }])}><Plus size={17} />Add column</button></div><div className="footerColumnEditors">{columns.map((column, index) => <FooterColumn key={column._id || index} column={column} index={index} pages={pages} onChange={(next) => { const all = [...columns]; all[index] = next; setColumns(all); }} onSave={() => save()} onRemove={() => save(columns.filter((_, itemIndex) => itemIndex !== index))} onMove={move} />)}</div>{!columns.length && <div className="panel">Add footer columns to replace the storefront default footer menus.</div>}</section>;
}

function FooterColumn({ column, index, pages, onChange, onSave, onRemove, onMove }) { const [query, setQuery] = useState(""); const matches = pages.filter((page) => page.title.toLowerCase().includes(query.toLowerCase())); const selected = column.pageIds || []; const toggle = (page) => { const id = String(page._id || page.slug); onChange({ ...column, pageIds: selected.includes(id) ? selected.filter((item) => item !== id) : [...selected, id] }); }; return <article className="panel footerColumnEditor" draggable onDragStart={(event) => event.dataTransfer.setData("text/plain", String(index))} onDragOver={(event) => event.preventDefault()} onDrop={(event) => onMove(Number(event.dataTransfer.getData("text/plain")), index)}><div className="panelHeader"><h3><GripVertical size={16} />Column {index + 1}</h3><button className="inlineButton" type="button" onClick={onRemove}><Trash2 size={15} /></button></div><label><span>Menu title</span><input value={column.title || ""} onChange={(event) => onChange({ ...column, title: event.target.value })} /></label><label><span>Column content</span><select value={column.type || "links"} onChange={(event) => onChange({ ...column, type: event.target.value })}><option value="text">Text</option><option value="links">Custom links</option><option value="pages">Pages</option></select></label>{column.type === "text" && <label><span>Text</span><RichTextEditor value={column.text || ""} onChange={(text) => onChange({ ...column, text })} compact /></label>}{column.type === "links" && <label><span>Links (Title | URL, one per line)</span><textarea value={(column.links || []).map((link) => `${link.label || ""} | ${link.url || ""}`).join("\n")} onChange={(event) => onChange({ ...column, links: event.target.value.split("\n").filter(Boolean).map((line) => { const [label, url] = line.split("|"); return { label: label?.trim() || "Link", url: url?.trim() || "#" }; }) })} /></label>}{column.type === "pages" && <div className="pagePicker"><input placeholder="Search pages" value={query} onChange={(event) => setQuery(event.target.value)} />{matches.map((page) => <label key={page._id || page.slug}><input type="checkbox" checked={selected.includes(String(page._id || page.slug))} onChange={() => toggle(page)} />{page.title}</label>)}{!matches.length && <small>No matching pages.</small>}</div>}<button className="primaryButton" type="button" onClick={onSave}><Save size={16} />Save column</button></article>; }

function RichTextEditor({ value, onChange, compact = false }) { const editor = useRef(null); useEffect(() => { if (editor.current && editor.current.innerHTML !== value) editor.current.innerHTML = value || ""; }, [value]); const command = (name, valueArg) => { editor.current?.focus(); document.execCommand(name, false, valueArg); onChange(editor.current?.innerHTML || ""); }; return <div className={`richEditor ${compact ? "compact" : ""}`}><div className="richToolbar"><button type="button" onClick={() => command("bold")}><b>B</b></button><button type="button" onClick={() => command("italic")}><i>I</i></button><button type="button" onClick={() => command("formatBlock", "h2")}>H2</button><button type="button" onClick={() => command("insertUnorderedList")}>• List</button><button type="button" onClick={() => { const url = window.prompt("Link URL"); if (url) command("createLink", url); }}>Link</button></div><div ref={editor} className="richEditorCanvas" contentEditable suppressContentEditableWarning onInput={(event) => onChange(event.currentTarget.innerHTML)} /></div>; }
const stripHtml = (value) => String(value || "").replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
