import { useEffect, useMemo, useState } from "react";
import { Eye, EyeOff, Search, X } from "lucide-react";
import { api, authStore } from "../services/api.js";

const money = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(value || 0);
const Field = ({ label, value }) => <div><small>{label}</small><strong>{value || "—"}</strong></div>;

export default function ResellerAdminPage() {
  const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null); const [details, setDetails] = useState(null); const [query, setQuery] = useState(""); const [message, setMessage] = useState(""); const [passwords, setPasswords] = useState({});
  const load = async () => setRows(await api.adminResellers());
  useEffect(() => { load().catch((error) => setMessage(error.message)); }, []);
  const filtered = useMemo(() => rows.filter((item) => `${item.fullName} ${item.businessName} ${item.email} ${item.mobile} ${item.resellerId}`.toLowerCase().includes(query.toLowerCase())), [rows, query]);
  const open = async (item) => { setSelected(item); setDetails(null); try { setDetails(await api.adminReseller(item._id)); } catch (error) { setMessage(error.message); } };
  const review = async (payload) => { try { await api.reviewReseller(selected._id, payload); await load(); setDetails(await api.adminReseller(selected._id)); setMessage("Reseller updated successfully."); } catch (error) { setMessage(error.message); } };
  const reveal = async (item) => { if (passwords[item._id]) { setPasswords((value) => ({ ...value, [item._id]: "" })); return; } try { const result = await api.revealResellerPassword(item._id); setPasswords((value) => ({ ...value, [item._id]: result.password })); } catch (error) { setMessage(error.message); } };
  const reset = async (item) => { if (!window.confirm(`Reset the password for ${item.fullName}? This also changes the linked customer login.`)) return; try { const result = await api.resetResellerPassword(item._id); setPasswords((value) => ({ ...value, [item._id]: result.password })); setMessage("Password reset successfully. Share it securely with the reseller."); } catch (error) { setMessage(error.message); } };
  return <section className="contentStack resellerAdminPage"><div className="panelHeader"><div><span className="eyebrow">Master</span><h2>Resellers</h2><p>Registered reseller accounts, login access, GST/KYC, catalog links, orders, withdrawals, and assignments.</p></div></div>{message && <div className="notice">{message}</div>}<label className="adminMasterSearch"><Search /><input placeholder="Search reseller name, business, email, mobile or ID" value={query} onChange={(event) => setQuery(event.target.value)} /></label><div className="panel tableWrap"><table><thead><tr><th>Reseller</th><th>Business</th><th>Contact</th><th>GST</th><th>KYC</th><th>Status</th><th>Password</th><th>Joined</th><th>Action</th></tr></thead><tbody>{filtered.map((item) => <tr key={item._id}><td><strong>{item.fullName}</strong><br /><small>{item.resellerId}</small></td><td>{item.businessName || "—"}</td><td>{item.email}<br /><small>{item.mobile}</small></td><td>{item.gstStatus === "gst" ? item.gstin || "Registered" : "Non-GST"}<br /><small>{item.gstVerificationStatus?.replaceAll("_", " ")}</small></td><td>{item.kyc?.status || "pending"}</td><td><span className={`status ${item.status}`}>{item.status}</span></td><td>{authStore.user?.role === "Super Admin" ? <><button className="passwordReveal" type="button" onClick={() => reveal(item)}>{passwords[item._id] ? <><strong className="temporaryPassword">{passwords[item._id]}</strong><EyeOff size={15} /></> : <><span>Protected</span><Eye size={15} /></>}</button><br /><button type="button" onClick={() => reset(item)}>Reset password</button></> : "Protected"}</td><td>{new Date(item.createdAt).toLocaleDateString("en-IN")}</td><td><button type="button" onClick={() => open(item)}><Eye size={15} /> View details</button></td></tr>)}{!filtered.length && <tr><td colSpan="9">No reseller accounts found.</td></tr>}</tbody></table></div>{selected && <DetailsModal selected={selected} details={details} close={() => { setSelected(null); setDetails(null); }} review={review} />}</section>;
}

function DetailsModal({ selected, details, close, review }) {
  return <div className="partnerDetailsOverlay"><section className="partnerDetailsDialog resellerDetailsDialog"><div className="panelHeader"><div><span className="eyebrow">{selected.resellerId}</span><h2>{selected.fullName}</h2><p>Complete reseller master record</p></div><button className="inlineButton" onClick={close}><X size={16} /> Close</button></div>{!details ? <p>Loading details…</p> : <><div className="resellerAdminDetailsGrid"><Field label="Business name" value={details.reseller.businessName} /><Field label="Email" value={details.reseller.email} /><Field label="Mobile" value={details.reseller.mobile} /><Field label="Address" value={details.reseller.address} /><Field label="PAN" value={details.reseller.pan} /><Field label="GST status" value={details.reseller.gstStatus} /><Field label="GSTIN" value={details.reseller.gstin} /><Field label="GST legal name" value={details.reseller.gstLegalName} /><Field label="GST state" value={details.reseller.gstState} /><Field label="GST verification" value={details.reseller.gstVerificationStatus} /><Field label="Payment method" value={details.reseller.paymentDetails?.method} /><Field label="Customer status" value={details.reseller.customer?.status} /></div>{details.reseller.gstCertificate && <p><a href={details.reseller.gstCertificate} target="_blank" rel="noreferrer">View GST certificate</a></p>}<div className="toolbar"><button onClick={() => review({ status: "active", kycStatus: "approved" })}>Approve &amp; activate</button><button onClick={() => review({ status: "rejected", kycStatus: "rejected", note: "Rejected during admin review" })}>Reject</button></div><div className="resellerDetailCounts"><Field label="Product share links" value={details.links.length} /><Field label="Attributed orders" value={details.orders.length} /><Field label="Withdrawals" value={details.withdrawals.length} /><Field label="Active permissions" value={details.assignments.length} /></div><h3>Assigned access</h3><div className="panel tableWrap"><table><thead><tr><th>Permission</th><th>Team</th><th>Team leader</th><th>Staff</th></tr></thead><tbody>{details.assignments.map((item) => <tr key={item._id}><td>{item.action.replaceAll("_", " ")}</td><td>{item.team?.name}</td><td>{item.teamLeader?.name}</td><td>{item.staff?.name || "Team leader"}</td></tr>)}{!details.assignments.length && <tr><td colSpan="4">No assignments.</td></tr>}</tbody></table></div><h3>Recent orders</h3><div className="panel tableWrap"><table><thead><tr><th>Order</th><th>Status</th><th>Customer total</th><th>Earning</th></tr></thead><tbody>{details.orders.slice(0, 10).map((order) => <tr key={order._id}><td>{order.orderNumber}</td><td>{order.status}</td><td>{money(order.grandTotal)}</td><td>{money(order.resellerAttribution?.earning)}</td></tr>)}{!details.orders.length && <tr><td colSpan="4">No attributed orders.</td></tr>}</tbody></table></div></>}</section></div>;
}
