import { useEffect, useState } from "react";
import { Copy, IndianRupee, MessageCircle, PackageCheck, Share2, WalletCards } from "lucide-react";
import { api, customerAuthStore } from "../services/api.js";

const money = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(value || 0);
const initialForm = { fullName: "", mobile: "", address: "", pan: "", gstStatus: "non-gst", gstin: "", paymentDetails: { method: "upi", upiId: "" }, kyc: { panDocument: "", addressDocument: "" }, termsAccepted: false, challengeId: "", otp: "" };

export default function ResellerPortal({ onBack }) {
  const [account, setAccount] = useState(null);
  const [dashboard, setDashboard] = useState(null);
  const [products, setProducts] = useState([]);
  const [links, setLinks] = useState([]);
  const [orders, setOrders] = useState([]);
  const [margins, setMargins] = useState({});
  const [form, setForm] = useState(initialForm);
  const [status, setStatus] = useState("");
  const [loading, setLoading] = useState(true);
  const load = async () => {
    if (!customerAuthStore.token) { setLoading(false); return; }
    try {
      const me = await api.resellerMe(); setAccount(me);
      const [summary, catalog, shared, sales] = await Promise.all([api.resellerDashboard(), api.resellerProducts(), api.resellerLinks(), api.resellerOrders()]);
      setDashboard(summary); setProducts(catalog); setLinks(shared); setOrders(sales);
    } catch (error) { if (!/reseller account/i.test(error.message)) setStatus(error.message); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);
  const requestOtp = async () => { try { const result = await api.resellerRegistrationOtp(); setForm({ ...form, challengeId: result.challengeId }); setStatus(result.message); } catch (error) { setStatus(error.message); } };
  const register = async (event) => { event.preventDefault(); try { await api.resellerRegister(form); setStatus("Reseller dashboard activated."); await load(); } catch (error) { setStatus(error.message); } };
  const generate = async (product) => { try { const result = await api.createResellerLink({ productId: product._id, margin: Number(margins[product._id] || 0) }); setLinks((current) => [result, ...current.filter((item) => item._id !== result._id)]); setStatus("Selling link generated."); } catch (error) { setStatus(error.message); } };
  const copy = async (url) => { await navigator.clipboard.writeText(url); setStatus("Link copied."); };
  if (loading) return <main className="resellerPortal"><p>Loading reseller workspace…</p></main>;
  if (!customerAuthStore.token) return <main className="resellerPortal"><button onClick={onBack}>Back</button><h1>Become an HRSBasket Reseller</h1><p>Please sign in with your customer account first, then open the reseller program again.</p></main>;
  if (!account) return <main className="resellerPortal"><button onClick={onBack}>Back</button><h1>Become an HRSBasket Reseller</h1><p>Sell without buying stock, packing parcels, or arranging delivery.</p>{status && <p className="resellerNotice">{status}</p>}<form className="resellerForm" onSubmit={register}><input required placeholder="Full name" value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })}/><input required placeholder="Mobile number" value={form.mobile} onChange={(e) => setForm({ ...form, mobile: e.target.value })}/><textarea required placeholder="Address" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })}/><input required placeholder="PAN" value={form.pan} onChange={(e) => setForm({ ...form, pan: e.target.value.toUpperCase() })}/><select value={form.gstStatus} onChange={(e) => setForm({ ...form, gstStatus: e.target.value })}><option value="non-gst">Non-GST</option><option value="gst">GST Registered</option></select>{form.gstStatus === "gst" && <input required placeholder="GSTIN" value={form.gstin} onChange={(e) => setForm({ ...form, gstin: e.target.value.toUpperCase() })}/>}<select value={form.paymentDetails.method} onChange={(e) => setForm({ ...form, paymentDetails: { method: e.target.value } })}><option value="upi">UPI</option><option value="bank">Bank account</option></select>{form.paymentDetails.method === "upi" ? <input required placeholder="UPI ID" onChange={(e) => setForm({ ...form, paymentDetails: { ...form.paymentDetails, upiId: e.target.value } })}/> : <><input required placeholder="Account holder" onChange={(e) => setForm({ ...form, paymentDetails: { ...form.paymentDetails, accountHolder: e.target.value } })}/><input required placeholder="Account number" onChange={(e) => setForm({ ...form, paymentDetails: { ...form.paymentDetails, accountNumber: e.target.value } })}/><input required placeholder="IFSC" onChange={(e) => setForm({ ...form, paymentDetails: { ...form.paymentDetails, ifsc: e.target.value.toUpperCase() } })}/></>}<input required placeholder="PAN document URL" onChange={(e) => setForm({ ...form, kyc: { ...form.kyc, panDocument: e.target.value } })}/><input required placeholder="Address proof URL" onChange={(e) => setForm({ ...form, kyc: { ...form.kyc, addressDocument: e.target.value } })}/>{!form.challengeId ? <button type="button" onClick={requestOtp}>Verify email with OTP</button> : <input required placeholder="Email OTP" value={form.otp} onChange={(e) => setForm({ ...form, otp: e.target.value })}/>}<label><input type="checkbox" checked={form.termsAccepted} onChange={(e) => setForm({ ...form, termsAccepted: e.target.checked })}/> I accept the reseller terms and conditions.</label><button type="submit" disabled={!form.challengeId}>Activate Reseller Dashboard</button></form></main>;
  return <main className="resellerPortal"><header><button onClick={onBack}>Storefront</button><div><h1>Reseller Dashboard</h1><p>{account.resellerId} · {account.fullName}</p></div></header>{status && <p className="resellerNotice">{status}</p>}<section className="resellerStats">{[["Total Earnings",dashboard?.totalEarnings,IndianRupee],["Pending",dashboard?.pendingEarnings,WalletCards],["Available",dashboard?.availableEarnings,WalletCards],["Paid",dashboard?.paidEarnings,PackageCheck]].map(([label,value,Icon])=><article key={label}><Icon/><span>{label}</span><strong>{money(value)}</strong></article>)}</section><h2>Add / Select Products</h2><section className="resellerProducts">{products.map((product)=>{const margin=Number(margins[product._id]||0);return <article key={product._id}>{product.mainImage&&<img src={product.mainImage} alt=""/>}<h3>{product.name}</h3><p>Base price: {money(product.resellerPricing.basePrice)} · Maximum margin: {money(product.resellerPricing.maximumMargin)}</p><label>Set your margin<input type="number" min="0" max={product.resellerPricing.maximumMargin} value={margins[product._id]||""} onChange={(e)=>setMargins({...margins,[product._id]:e.target.value})}/></label><strong>Customer price: {money(Number(product.resellerPricing.basePrice)+margin)}</strong><span>Your earning: {money(margin)}</span><button onClick={()=>generate(product)}>Generate Selling Link</button></article>})}</section><h2>My Shared Links</h2><section className="resellerLinks">{links.map((link)=>{const url=link.url||`${window.location.origin}/#/resell/${link.code}`;const message=encodeURIComponent(`${link.product?.name||"HRSBasket product"} — ${money(link.customerPrice)}\n${url}`);return <article key={link._id}><strong>{link.product?.name}</strong><span>{money(link.customerPrice)}</span><button onClick={()=>copy(url)}><Copy/> Copy Link</button><a href={`https://wa.me/?text=${message}`} target="_blank" rel="noreferrer"><MessageCircle/> WhatsApp</a><button onClick={()=>navigator.share?.({title:link.product?.name,url})}><Share2/> Share</button></article>})}</section><h2>My Orders &amp; Earnings</h2><section className="resellerOrders">{orders.map((order)=><article key={order._id}><strong>{order.orderNumber}</strong><span>{order.status}</span><span>Order {money(order.grandTotal)}</span><span>Margin {money(order.resellerAttribution?.margin)}</span><span>Final earning {money(order.resellerAttribution?.finalEarning)}</span><span>{order.resellerAttribution?.status}</span></article>)}</section></main>;
}
