import { Check, Star, X } from "lucide-react";
import { useEffect, useState } from "react";
import { api } from "../services/api.js";
import TablePagination from "../components/TablePagination.jsx";

const image = (product) => product?.imageVariants?.admin || product?.imageVariants?.storefront || product?.mainImage || "/images/e-commerce/home/product4.png";

export default function ReviewAdminPage() {
  const [status, setStatus] = useState("pending");
  const [data, setData] = useState({ items: [], pagination: { page: 1, pages: 1, total: 0, limit: 20 } });
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState("");
  const load = async (page = 1, nextStatus = status) => { setLoading(true); try { setData(await api.adminReviews({ status: nextStatus, page, limit: 20 })); } catch (error) { setNotice(error.message); } finally { setLoading(false); } };
  useEffect(() => { load(1, status); }, [status]);
  const moderate = async (review, nextStatus) => { const note = nextStatus === "rejected" ? window.prompt("Reason for rejecting this review:") : ""; if (nextStatus === "rejected" && note === null) return; try { await api.moderateReview(review._id, { status: nextStatus, note }); setNotice(`Review ${nextStatus} successfully.`); await load(data.pagination.page, status); } catch (error) { setNotice(error.message); } };
  return <section className="contentStack reviewModerationPage"><div className="panelHeader"><div><span className="eyebrow">Customer content</span><h2>Reviews &amp; Ratings Approval</h2><p>Only approved reviews and ratings are shown on the storefront.</p></div></div>{notice && <div className="notice">{notice}</div>}<div className="reviewModerationTabs">{["pending", "approved", "rejected"].map((value) => <button className={status === value ? "active" : ""} type="button" key={value} onClick={() => setStatus(value)}>{value}</button>)}</div>{loading ? <div className="panel tableLoadingState"><span className="storefrontLoadingSpinner" />Loading reviews…</div> : <div className="reviewModerationList">{data.items.map((review) => <article className="panel" key={review._id}><img src={image(review.product)} alt="" /><div className="reviewModerationBody"><div className="ratingRow">{[1,2,3,4,5].map((value) => <Star key={value} size={16} fill={value <= review.rating ? "currentColor" : "none"} />)}<strong>{review.rating}/5</strong>{review.sellerRating && <span>Store: {review.sellerRating}/5</span>}</div><h3>{review.product?.name || "Deleted product"}</h3><p>{review.comment}</p><small>{review.customer?.name || "Customer"} · {review.customer?.email || ""} · Order {review.order?.orderNumber || "—"}</small><small>{review.seller ? `${review.seller.companyName} · ${review.seller.sellerNumber}` : "Admin product"} · {new Date(review.createdAt).toLocaleString("en-IN")}</small>{review.moderationNote && <small>Moderation note: {review.moderationNote}</small>}</div><div className="reviewModerationActions">{review.status !== "approved" && <button className="primaryButton" type="button" onClick={() => moderate(review, "approved")}><Check size={16} /> Approve</button>}{review.status !== "rejected" && <button className="secondaryButton" type="button" onClick={() => moderate(review, "rejected")}><X size={16} /> Reject</button>}</div></article>)}{!data.items.length && <div className="panel accountEmpty"><Star size={30} /><h3>No {status} reviews</h3></div>}</div>}{!loading && data.pagination.pages > 1 && <TablePagination total={data.pagination.total} page={data.pagination.page} pageSize={data.pagination.limit} pageSizes={[20]} onPageChange={(page) => load(page, status)} onPageSizeChange={() => {}} />}</section>;
}
