import { useEffect, useState } from "react";
import { AlertTriangle, BriefcaseBusiness, Clock3, Headphones, PackageCheck, UsersRound } from "lucide-react";
import { api } from "../services/api.js";

export default function StaffWorkDashboard({ onOpenAccess }) {
  const [data,setData]=useState(null); const [error,setError]=useState("");
  useEffect(()=>{api.staffWorkDashboard().then(setData).catch(err=>setError(err.message))},[]);
  if(error)return <div className="notice">{error}</div>; if(!data)return <div className="panel">Loading your assigned workspace…</div>;
  const cards=[["Active assignments",data.activeAssignments,BriefcaseBusiness],["Open support tickets",data.openTickets,Headphones],["Pending product approvals",data.pendingProductApprovals,PackageCheck],["Overdue items",data.overdueItems,AlertTriangle],["Expiring in 7 days",data.expiringSoon,Clock3],[data.role==="Team Leader"?"Team staff":"My team",data.role==="Team Leader"?data.staffCount:data.teamCount,UsersRound]];
  return <section className="staffRoleDashboard contentStack"><div className="panelHeader"><div><span className="eyebrow">{data.role} workspace</span><h2>{data.role==="Team Leader"?"Team Operations Dashboard":"My Work Dashboard"}</h2><p>Only entities, modules and actions granted through active assignments are shown.</p></div>{data.role==="Team Leader"&&<button className="primaryButton" onClick={onOpenAccess}>Manage team &amp; delegation</button>}</div><div className="staffDashboardStats">{cards.map(([label,value,Icon])=><article key={label}><Icon/><span>{label}</span><strong>{value}</strong></article>)}</div><div className="staffDashboardEntities">{Object.entries(data.entityCounts).map(([type,count])=><article key={type}><small>My {type.toLowerCase()}s</small><strong>{count}</strong></article>)}</div>{data.role==="Team Leader"&&<div className="panel tableWrap"><h3>Team roster</h3><table><thead><tr><th>Team</th><th>Staff</th><th>Status</th></tr></thead><tbody>{data.teams.flatMap(team=>team.members.map(member=><tr key={`${team._id}-${member._id}`}><td>{team.name}</td><td>{member.name}<br/><small>{member.employeeCode}</small></td><td>{member.staffStatus}</td></tr>))}</tbody></table></div>}<div className="panel tableWrap"><h3>My active access</h3><table><thead><tr><th>Entity</th><th>Module</th><th>Actions</th><th>Staff</th><th>Expiry</th></tr></thead><tbody>{data.assignments.map(item=><tr key={item._id}><td>{item.entityType}<br/><small>{item.entity?.companyName||item.entity?.businessName||item.entity?.fullName||item.entity?.name||item.entity?.email}</small></td><td>{item.action.replaceAll("_"," ")}</td><td>{item.permissions.join(" · ")}</td><td>{item.staff?.name||"Team Leader"}</td><td>{item.effectiveUntil?new Date(item.effectiveUntil).toLocaleDateString("en-IN"):"No expiry"}</td></tr>)}</tbody></table></div></section>;
}
