import { router,useLocalSearchParams } from 'expo-router';
import { useEffect,useState } from 'react';
import { ActivityIndicator,Image,ScrollView,Text,View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { Screen } from '@/components/Screen';
import { Button,Chip,Field } from '@/components/Ui';
import { api,mediaUrl } from '@/lib/api';
import { money } from '@/lib/commerce';
import type { Order } from '@/types';
import { colors } from '@/theme';
import { useAuth } from '@/context/AuthContext';
const reasons=['Damaged product','Wrong item received','Product not as described','Quality issue','Other'];const evidenceTypes=['Unboxing Photo','Unboxing Video','Product Damage Video','Product Label Photo'];
export default function OrderDetail(){
 const {id,number}=useLocalSearchParams<{id:string;number?:string}>();const {ready,customer}=useAuth();const [order,setOrder]=useState<Order>();const [tracking,setTracking]=useState<any>();const [error,setError]=useState('');const [target,setTarget]=useState<number>();const [reason,setReason]=useState(reasons[0]);const [category,setCategory]=useState(evidenceTypes[0]);const [comments,setComments]=useState('');const [evidence,setEvidence]=useState<{category:string;url:string}[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const load=async()=>{setError('');try{const result=await api.order(id);setOrder(result.order);api.tracking(id).then(setTracking).catch(e=>setError(e.message))}catch(e:any){setError(e.message)}};
 useEffect(()=>{if(!ready)return;if(!customer)router.replace('/login');else void load()},[id,ready,customer?.id]);
 const upload=async()=>{setBusy(true);setMessage('');try{const video=category.includes('Video');const picked=await DocumentPicker.getDocumentAsync({type:video?'video/*':'image/*',copyToCacheDirectory:true});if(!picked.canceled){const file=picked.assets[0];const r=await api.upload(file,video);setEvidence(x=>[...x,{category,url:r.url}])}}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const requestReturn=async()=>{if(target===undefined||!order)return;setBusy(true);try{const item=order.items[target];const productId=typeof item.product==='string'?item.product:item.product?._id;if(!productId)throw new Error('Product unavailable');await api.returnItem(id,productId,{reason,comments,evidence});setTarget(undefined);setEvidence([]);setComments('');setMessage('Return request submitted');await load()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 return <Screen title={order?.orderNumber||number||'Order details'} back><ScrollView contentContainerStyle={{padding:20,gap:16,paddingBottom:40,maxWidth:800,width:'100%',alignSelf:'center'}}>{error&&<><Text style={{color:colors.danger}}>{error}</Text><Button title="Retry" onPress={load}/></>}{!order&&!error?<ActivityIndicator/>:order&&<><Text style={{fontSize:24,fontWeight:'900'}}>{order.orderNumber}</Text><Text>{order.status} · {new Date(order.createdAt).toLocaleDateString('en-IN')}</Text><Text style={{fontSize:21,fontWeight:'800'}}>Total {money(order.grandTotal)}</Text>{order.items.map((item,i)=><View key={i} style={{backgroundColor:'white',padding:16,borderRadius:14,gap:12}}><View style={{flexDirection:'row',gap:12}}>{typeof item.product==='object'&&<Image source={{uri:mediaUrl(item.product.mainImage)}} style={{width:70,height:70,borderRadius:10}}/>}<View style={{flex:1}}><Text style={{fontWeight:'800'}}>{item.name}</Text><Text>{item.quantity} × {money(item.price)}</Text><Text>{item.sellerStatus||order.status}</Text></View></View>{typeof item.product==='object'&&<Button title="View product / review" variant="outline" onPress={()=>router.push({pathname:'/product/[id]',params:{id:(item.product as any)._id}})}/>} {item.returnRequest?.status?<Text>Return: {item.returnRequest.status}</Text>:item.returnApplicable&&item.returnDays&& (item.sellerStatus==='Delivered'||order.status==='Delivered')?<Button title="Request return" variant="outline" onPress={()=>{setTarget(i);setEvidence([]);setMessage('')}}/>:null}</View>)}<Text style={{fontSize:20,fontWeight:'900'}}>Tracking timeline</Text>{!tracking&&!error?<ActivityIndicator/>:(tracking?.activities||[]).map((a:any,i:number)=><View key={i} style={{padding:14,borderLeftWidth:3,borderColor:colors.primary,gap:4}}><Text style={{fontWeight:'800'}}>{a.activity||a.title||a.status}</Text><Text>{a.date||a.comment||a.details}</Text></View>)}{tracking?.awb&&<Text>AWB: {tracking.awb}</Text>}</>}
 {target!==undefined&&<View style={{gap:12,padding:16,backgroundColor:colors.primarySoft,borderRadius:16}}><Text style={{fontSize:20,fontWeight:'900'}}>Return {order?.items[target].name}</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{reasons.map(r=><Chip key={r} label={r} selected={r===reason} onPress={()=>setReason(r)}/>)}</View><Field label="Additional comments" value={comments} onChangeText={setComments} multiline/><Text>Evidence category</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{evidenceTypes.map(c=><Chip key={c} label={c} selected={c===category} onPress={()=>setCategory(c)}/>)}</View><Button title="Upload evidence" variant="outline" loading={busy} disabled={evidence.length>=10} onPress={upload}/>{evidence.map((e,i)=><View key={i}><Text>{e.category}</Text><Button title="Remove file" variant="ghost" onPress={()=>setEvidence(x=>x.filter((_,j)=>i!==j))}/></View>)}<Button title="Submit return request" loading={busy} disabled={!evidence.length} onPress={requestReturn}/><Button title="Cancel" variant="outline" onPress={()=>setTarget(undefined)}/></View>}{message&&<Text style={{color:colors.primary}}>{message}</Text>}</ScrollView></Screen>;
}
